// SPDX-License-Identifier: GPL-2.0

mod continuation;

use core::{
    cell::Cell,
    mem, //
};

use kernel::{
    device,
    dma::{
        Coherent,
        CoherentBox,
        DmaAddress, //
    },
    fmt,
    io::{
        io_project,
        poll::read_poll_timeout,
        Io, //
    },
    new_mutex,
    prelude::*,
    ptr,
    sync::{
        aref::ARef,
        barrier::{
            dma_mb,
            Full, //
        },
        Mutex, //
    },
    time::{
        Delta,
        Instant,
        Monotonic, //
    },
    transmute::{
        AsBytes,
        FromBytes, //
    },
};

use continuation::{
    ContinuationRecord,
    SplitState, //
};

use pin_init::pin_init_scope;

use crate::{
    driver::Bar0,
    gsp::{
        fw::{
            GspGmcMsgElement,
            GspMsgElement,
            MsgFunction,
            MsgqTxHeaderV2,
            GSP_MSG_QUEUE_ELEMENT_SIZE_MAX, //
        },
        PteArray,
        GSP_PAGE_SHIFT,
        GSP_PAGE_SIZE, //
    },
    num,
    sbuffer::SBufferIter, //
};

use super::regs;

/// Marker type representing the absence of a reply for a command. Commands using this as their
/// reply type are sent using [`Cmdq::send_command_no_wait`].
pub(crate) struct NoReply;

/// Trait implemented by types representing a command to send to the GSP.
///
/// The main purpose of this trait is to provide [`Cmdq`] with the information it needs to send
/// a given command.
///
/// [`CommandToGsp::init`] in particular is responsible for initializing the command directly
/// into the space reserved for it in the command queue buffer.
///
/// Some commands may be followed by a variable-length payload. For these, the
/// [`CommandToGsp::variable_payload_len`] and [`CommandToGsp::init_variable_payload`] need to be
/// defined as well.
pub(crate) trait CommandToGsp {
    /// Function identifying this command to the GSP.
    const FUNCTION: MsgFunction;

    /// Whether the send path logs this command as an async send.
    ///
    /// This selects the debug line only, and changes nothing on the wire. Set it on commands
    /// sent without waiting for a reply.
    const IS_ASYNC: bool = false;

    /// Type generated by [`CommandToGsp::init`], to be written into the command queue buffer.
    type Command: FromBytes + AsBytes;

    /// Type of the reply expected from the GSP, or [`NoReply`] for commands that don't
    /// have a reply.
    type Reply;

    /// Error type returned by [`CommandToGsp::init`].
    type InitError;

    /// In-place command initializer responsible for filling the command in the command queue
    /// buffer.
    fn init(&self) -> impl Init<Self::Command, Self::InitError>;

    /// Size of the variable-length payload following the command structure generated by
    /// [`CommandToGsp::init`].
    ///
    /// Most commands don't have a variable-length payload, so this is zero by default.
    fn variable_payload_len(&self) -> usize {
        0
    }

    /// Method initializing the variable-length payload.
    ///
    /// The command buffer is circular, which means that we may need to jump back to its beginning
    /// while in the middle of a command. For this reason, the variable-length payload is
    /// initialized using a [`SBufferIter`].
    ///
    /// This method will receive a buffer of the length returned by
    /// [`CommandToGsp::variable_payload_len`], and must write every single byte of it. Leaving
    /// unwritten space will lead to an error.
    ///
    /// Most commands don't have a variable-length payload, so this does nothing by default.
    fn init_variable_payload(
        &self,
        _dst: &mut SBufferIter<core::array::IntoIter<&mut [u8], 2>>,
    ) -> Result {
        Ok(())
    }

    /// Total size of the command (including its variable-length payload) without the
    /// [`GspMsgElement`] header.
    fn size(&self) -> usize {
        size_of::<Self::Command>() + self.variable_payload_len()
    }
}

/// Trait representing messages received from the GSP.
///
/// This trait tells [`Cmdq::await_msg`] how it can receive a given type of message.
pub(crate) trait MessageFromGsp: Sized {
    /// Function identifying this message from the GSP.
    const FUNCTION: MsgFunction;

    /// Error type returned by [`MessageFromGsp::read`].
    type InitError;

    /// Type containing the raw message to be read from the message queue.
    type Message: FromBytes;

    /// Method reading the message from the message queue and returning it.
    ///
    /// From a `Self::Message` and a [`SBufferIter`], constructs an instance of `Self` and returns
    /// it.
    fn read(
        msg: &Self::Message,
        sbuffer: &mut SBufferIter<core::array::IntoIter<&[u8], 2>>,
    ) -> Result<Self, Self::InitError>;
}

/// Number of GSP pages making the [`Msgq`].
pub(crate) const MSGQ_NUM_PAGES: u32 = 0x3f;

/// Circular buffer of a [`Msgq`].
///
/// This area of memory is to be shared between the driver and the GSP to exchange commands or
/// messages.
#[repr(C, align(0x1000))]
#[derive(Debug)]
struct MsgqData {
    data: [[u8; GSP_PAGE_SIZE]; num::u32_as_usize(MSGQ_NUM_PAGES)],
}

// Annoyingly we are forced to use a literal to specify the alignment of
// `MsgqData`, so check that it corresponds to the actual GSP page size here.
static_assert!(align_of::<MsgqData>() == GSP_PAGE_SIZE);

/// Unidirectional message queue.
///
/// Contains the data for a message queue, that either the driver or GSP writes to.
///
/// Msgq v2 keeps the ring pointers in BAR0, so `tx` carries the queue geometry alone. `msgq` is
/// aligned to [`GSP_PAGE_SIZE`], so the bytes between the two are zero padding.
#[repr(C)]
// There is no struct defined for this in the open-gpu-kernel-source headers.
// Instead it is defined by code in `GspMsgQueuesInit()`.
struct Msgq {
    /// Header describing the queue geometry.
    tx: MsgqTxHeaderV2,
    /// The message queue proper.
    msgq: MsgqData,
}

/// Structure shared between the driver and the GSP and containing the command and message queues.
#[repr(C)]
struct GspMem {
    /// Self-mapping page table entries.
    ptes: PteArray<{ Self::PTE_ARRAY_SIZE }>,
    /// CPU queue: the driver writes commands here, and the GSP reads them. It also contains the
    /// write and read pointers that the CPU updates. This means that the read pointer here is an
    /// index into the GSP queue.
    ///
    /// This member is read-only for the GSP.
    cpuq: Msgq,
    /// GSP queue: the GSP writes messages here, and the driver reads them. It also contains the
    /// write and read pointers that the GSP updates. This means that the read pointer here is an
    /// index into the CPU queue.
    ///
    /// This member is read-only for the driver.
    gspq: Msgq,
}

impl GspMem {
    const PTE_ARRAY_SIZE: usize = GSP_PAGE_SIZE / size_of::<u64>();
}

// SAFETY: These structs don't meet the no-padding requirements of AsBytes but
// that is not a problem because they are not used outside the kernel.
unsafe impl AsBytes for GspMem {}

// SAFETY: These structs don't meet the no-padding requirements of FromBytes but
// that is not a problem because they are not used outside the kernel.
unsafe impl FromBytes for GspMem {}

/// Wrapper around [`GspMem`] to share it with the GPU using a [`Coherent`].
///
/// This provides the low-level functionality to communicate with the GSP, including allocation of
/// queue space to write messages to and management of read/write pointers.
///
/// This is shared with the GSP, with clear ownership rules regarding the command queues:
///
/// * The driver owns (i.e. can write to) the part of the CPU message queue between the CPU write
///   pointer and the GSP read pointer. This region is returned by [`Self::driver_write_area`].
/// * The driver owns (i.e. can read from) the part of the GSP message queue between the CPU read
///   pointer and the GSP write pointer. This region is returned by [`Self::driver_read_area`].
struct DmaGspMem(Coherent<GspMem>);

impl DmaGspMem {
    /// Allocate a new instance and map it for `dev`.
    fn new(dev: &device::Device<device::Bound>) -> Result<Self> {
        const MSGQ_SIZE: u32 = num::usize_into_u32::<{ size_of::<Msgq>() }>();
        const MSG_SIZE: u32 = num::usize_into_u32::<GSP_PAGE_SIZE>();
        const ENTRY_OFF: u32 = num::usize_into_u32::<{ mem::offset_of!(Msgq, msgq) }>();

        let mut gsp_mem = CoherentBox::<GspMem>::zeroed(dev, GFP_KERNEL)?;
        gsp_mem.cpuq.tx = MsgqTxHeaderV2::new(MSGQ_SIZE, MSG_SIZE, MSGQ_NUM_PAGES, ENTRY_OFF);

        let gsp_mem: Coherent<_> = gsp_mem.into();
        PteArray::init(io_project!(gsp_mem, .ptes), gsp_mem.dma_address())?;

        Ok(Self(gsp_mem))
    }

    /// Allocates a region on the command queue that is large enough to send a command of `size`
    /// bytes, waiting for space to become available based on the provided timeout.
    ///
    /// This returns a [`GspCommand`] ready to be written to by the caller.
    ///
    /// # Errors
    ///
    /// - `EMSGSIZE` if the command is larger than [`GSP_MSG_QUEUE_ELEMENT_SIZE_MAX`].
    /// - `ETIMEDOUT` if space does not become available within the timeout.
    /// - `EIO` if the command header is not properly aligned.
    fn allocate_command<H: FromBytes + AsBytes>(
        &mut self,
        bar: Bar0<'_>,
        size: usize,
        timeout: Delta,
    ) -> Result<GspCommand<'_, H>> {
        if size_of::<H>() + size > GSP_MSG_QUEUE_ELEMENT_SIZE_MAX {
            return Err(EMSGSIZE);
        }
        read_poll_timeout(
            || Ok(Self::driver_write_area_size_v2(bar)),
            |available_bytes| *available_bytes >= size_of::<H>() + size,
            Delta::from_micros(1),
            timeout,
        )?;

        // Get the current writable area as an array of bytes.
        let (slice_1, slice_2) = {
            let (slice_1, slice_2) = self.driver_write_area_v2(bar);

            (slice_1.as_flattened_mut(), slice_2.as_flattened_mut())
        };

        // Extract area for the message element header.
        let (header, slice_1) = H::from_bytes_mut_prefix(slice_1).ok_or(EIO)?;

        // Create the contents area.
        let (slice_1, slice_2) = if slice_1.len() > size {
            // Contents fits entirely in `slice_1`.
            (&mut slice_1[..size], &mut slice_2[0..0])
        } else {
            // Need all of `slice_1` and some of `slice_2`.
            let slice_2_len = size - slice_1.len();
            (slice_1, &mut slice_2[..slice_2_len])
        };

        Ok(GspCommand {
            header,
            contents: (slice_1, slice_2),
        })
    }
}

// Msgq v2 internals.
//
// The four ring pointers are monotonic `u32` counters in the BAR0 registers declared in
// `gsp/regs.rs`, reduced to a slot index with `% MSGQ_NUM_PAGES` only where one is used. Because
// they do not wrap at the ring size, `head == tail` means empty and a difference of
// `MSGQ_NUM_PAGES` means full, so every slot is usable.
//
// TODO: reset recovery across suspend and resume. A power cycle loses the driver's counters as
// well, so both ends have to be re-established rather than restored.
impl DmaGspMem {
    // ORDERING: `readl` ends in `dma_rmb()`, which supplies the LOAD->LOAD ordering between this
    // read and the data read that follows it.
    fn gsp_write_ptr_v2(bar: Bar0<'_>) -> u32 {
        *bar.read(regs::NV_PGSP_MSGQ_HEAD).address()
    }

    fn gsp_read_ptr_v2(bar: Bar0<'_>) -> u32 {
        let ptr = *bar.read(regs::NV_PGSP_QUEUE_TAIL).address();

        // ORDERING: LOAD->STORE ordering needed to order `gsp_read_ptr_v2` read before data
        // write. `readl` carries LOAD->LOAD only.
        dma_mb(Full);

        ptr
    }

    fn cpu_read_ptr_v2(bar: Bar0<'_>) -> u32 {
        *bar.read(regs::NV_PGSP_MSGQ_TAIL).address()
    }

    fn cpu_write_ptr_v2(bar: Bar0<'_>) -> u32 {
        *bar.read(regs::NV_PGSP_QUEUE_HEAD).address()
    }

    /// Writes back the two counters the driver owns, after a GSP reset has zeroed all four.
    ///
    /// GSP-RM restores `NV_PGSP_MSGQ_HEAD` and `NV_PGSP_QUEUE_TAIL` from its own state when it
    /// resumes, and continues counting from where it left off rather than from zero. The driver
    /// owns the other two and has to do the same, or the two ends address different slots.
    fn restore_cpu_ptrs_v2(bar: Bar0<'_>, write_ptr: u32, read_ptr: u32) {
        // ORDERING: LOAD->STORE ordering needed to order the read-pointer write after the data
        // read, as in `advance_cpu_read_ptr_v2`.
        dma_mb(Full);

        bar.write_reg(regs::NV_PGSP_MSGQ_TAIL::zeroed().with_address(read_ptr));
        bar.write_reg(regs::NV_PGSP_QUEUE_HEAD::zeroed().with_address(write_ptr));
    }

    fn advance_cpu_read_ptr_v2(bar: Bar0<'_>, count: u32) {
        let new_rptr = Self::cpu_read_ptr_v2(bar).wrapping_add(count);

        // ORDERING: LOAD->STORE ordering needed to order `cpu_read_ptr_v2` write after data read,
        // so the GSP cannot recycle the slots while the driver is still reading them. `writel`
        // carries STORE->STORE only.
        dma_mb(Full);

        bar.write_reg(regs::NV_PGSP_MSGQ_TAIL::zeroed().with_address(new_rptr));
    }

    fn advance_cpu_write_ptr_v2(bar: Bar0<'_>, count: u32) {
        let new_wptr = Self::cpu_write_ptr_v2(bar).wrapping_add(count);

        // ORDERING: `writel` begins with `dma_wmb()`, which supplies the STORE->STORE ordering
        // between the data writes and this register write. Writing the head register doubles as
        // the GSP doorbell.
        bar.write_reg(regs::NV_PGSP_QUEUE_HEAD::zeroed().with_address(new_wptr));
    }

    /// Returns the region of the CPU message queue that the driver is currently allowed to write
    /// to.
    ///
    /// As the message queue is a circular buffer, the region may be discontiguous in memory. In
    /// that case the second slice will have a non-zero length.
    fn driver_write_area_v2(
        &mut self,
        bar: Bar0<'_>,
    ) -> (&mut [[u8; GSP_PAGE_SIZE]], &mut [[u8; GSP_PAGE_SIZE]]) {
        let raw_w = Self::cpu_write_ptr_v2(bar);
        let raw_r = Self::gsp_read_ptr_v2(bar);

        let used = raw_w.wrapping_sub(raw_r);
        let avail = num::u32_as_usize(MSGQ_NUM_PAGES.saturating_sub(used));
        let w_slot = num::u32_as_usize(raw_w % MSGQ_NUM_PAGES);

        // Pointer to the first entry of the CPU message queue.
        let data = ptr::project!(mut self.0.as_mut_ptr(), .cpuq.msgq.data[build: 0]);

        // SAFETY:
        // - `data` points to the `MSGQ_NUM_PAGES` initialized entries of the CPU message queue.
        // - The returned slices cover the `avail` free slots from the write pointer on, which
        //   the GSP does not read until `advance_cpu_write_ptr_v2` publishes them.
        // - `split_at_mut` gives two non-overlapping halves, and the `&mut self` borrow lasts as
        //   long as the returned slices, so nothing else hands out the same region.
        let data =
            unsafe { core::slice::from_raw_parts_mut(data, num::u32_as_usize(MSGQ_NUM_PAGES)) };
        let (before_w, after_w) = data.split_at_mut(w_slot);

        let in_after = avail.min(after_w.len());
        let in_before = avail - in_after;
        (&mut after_w[..in_after], &mut before_w[..in_before])
    }

    /// Returns the size, in bytes, of the region of the CPU message queue that the driver is
    /// currently allowed to write to.
    fn driver_write_area_size_v2(bar: Bar0<'_>) -> usize {
        let used = Self::cpu_write_ptr_v2(bar).wrapping_sub(Self::gsp_read_ptr_v2(bar));
        let slots = MSGQ_NUM_PAGES.saturating_sub(used);
        num::u32_as_usize(slots) * GSP_PAGE_SIZE
    }

    /// Returns the region of the GSP message queue that the driver is currently allowed to read
    /// from.
    ///
    /// As the message queue is a circular buffer, the region may be discontiguous in memory. In
    /// that case the second slice will have a non-zero length.
    fn driver_read_area_v2(
        &self,
        bar: Bar0<'_>,
    ) -> (&[[u8; GSP_PAGE_SIZE]], &[[u8; GSP_PAGE_SIZE]]) {
        let raw_w = Self::gsp_write_ptr_v2(bar);
        let raw_r = Self::cpu_read_ptr_v2(bar);

        // A difference wider than the ring means the GSP has been reset and has not yet written
        // its own counter back, so the read pointer is momentarily ahead of it. Report nothing
        // readable, which holds the callers in their poll until GSP-RM restores the real value.
        let pending = raw_w.wrapping_sub(raw_r);
        let avail = if pending > MSGQ_NUM_PAGES {
            0
        } else {
            num::u32_as_usize(pending)
        };
        let r_slot = num::u32_as_usize(raw_r % MSGQ_NUM_PAGES);

        // Pointer to the first entry of the GSP message queue.
        let data = ptr::project!(self.0.as_ptr(), .gspq.msgq.data[build: 0]);

        // SAFETY:
        // - `data` points to the `MSGQ_NUM_PAGES` initialized entries of the GSP message queue.
        // - The returned slices cover the `avail` slots the GSP has already written and does not
        //   write again until `advance_cpu_read_ptr_v2` releases them.
        let data = unsafe { core::slice::from_raw_parts(data, num::u32_as_usize(MSGQ_NUM_PAGES)) };
        let (before_r, after_r) = data.split_at(r_slot);

        let in_after = avail.min(after_r.len());
        let in_before = avail - in_after;
        (&after_r[..in_after], &before_r[..in_before])
    }
}

/// A command ready to be sent on the command queue.
///
/// `H` is the element header this command carries: [`GspMsgElement`] for an RM RPC.
///
/// This is the type returned by [`DmaGspMem::allocate_command`].
struct GspCommand<'a, H = GspMsgElement> {
    // Writable reference to the header of the command.
    header: &'a mut H,
    // Writable slices to the contents of the command. The second slice is zero unless the command
    // loops over the command queue.
    contents: (&'a mut [u8], &'a mut [u8]),
}

/// A message ready to be processed from the message queue.
///
/// This is the type returned by [`CmdqInner::wait_for_msg`].
struct GspMessage<'a> {
    // Reference to the header of the message.
    header: &'a GspMsgElement,
    // Slices to the contents of the message. The second slice is zero unless the message loops
    // over the message queue.
    contents: (&'a [u8], &'a [u8]),
}

/// A GMC message ready to be processed from the message queue.
///
/// This is the type returned by [`CmdqInner::wait_for_gmc_msg`].
struct GmcMessage<'a> {
    // Reference to the header of the message.
    header: &'a GspGmcMsgElement,
    // Slices of the payload following the `GmcApiHeader`. The second slice is empty unless the
    // payload wraps around the end of the message queue.
    contents: (&'a [u8], &'a [u8]),
}

/// State of the msgq v2 pointer registers after a GMC dispatch handler has run.
///
/// A handler that resets the GSP falcon zeroes all four registers, so a read-modify-write on
/// them afterwards would restart the driver's side of the ring at zero.
/// [`CmdqInner::receive_gmc_and_dispatch`] writes the captured values back instead.
#[derive(PartialEq, Eq)]
pub(crate) enum QueuePointers {
    /// The handler left the pointer registers alone.
    Unchanged,
    /// The handler reset the GSP, which zeroed the pointer registers.
    Reset,
}

/// GSP command queue.
///
/// Provides the ability to send commands and receive messages from the GSP using a shared memory
/// area.
#[pin_data]
pub(crate) struct Cmdq {
    /// Inner mutex-protected state.
    #[pin]
    inner: Mutex<CmdqInner>,
    /// DMA address of the command queue's shared memory region.
    pub(super) dma_addr: DmaAddress,
}

impl Cmdq {
    /// Offset of the data after the PTEs.
    const POST_PTE_OFFSET: usize = core::mem::offset_of!(GspMem, cpuq);

    /// Offset of command queue ring buffer.
    pub(crate) const CMDQ_OFFSET: usize = core::mem::offset_of!(GspMem, cpuq)
        + core::mem::offset_of!(Msgq, msgq)
        - Self::POST_PTE_OFFSET;

    /// Offset of message queue ring buffer.
    pub(crate) const STATQ_OFFSET: usize = core::mem::offset_of!(GspMem, gspq)
        + core::mem::offset_of!(Msgq, msgq)
        - Self::POST_PTE_OFFSET;

    /// Number of page table entries for the GSP shared region.
    pub(crate) const NUM_PTES: usize = size_of::<GspMem>() >> GSP_PAGE_SHIFT;

    /// Default timeout for receiving a message from the GSP.
    pub(super) const RECEIVE_TIMEOUT: Delta = Delta::from_secs(5);

    /// Creates a new command queue for `dev`.
    pub(crate) fn new(dev: &device::Device<device::Bound>) -> impl PinInit<Self, Error> + '_ {
        pin_init_scope(move || {
            let gsp_mem = DmaGspMem::new(dev)?;

            Ok(try_pin_init!(Self {
                dma_addr: gsp_mem.0.dma_address(),
                inner <- new_mutex!(CmdqInner {
                    dev: dev.into(),
                    gsp_mem,
                    rpc_seq: 0,
                    tx_async_seq: 0,
                    rx_event_seq: 0,
                    poisoned: Cell::new(false),
                }),
            }))
        })
    }

    /// Sends `command` to the GSP and waits for the reply.
    ///
    /// An event that arrives before the reply is consumed, and logged when it reports an error.
    ///
    /// The queue is locked for the entire send+receive cycle to ensure that no other command can
    /// be interleaved.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if space does not become available to send the command, or if the reply does
    ///   not arrive within [`Self::RECEIVE_TIMEOUT`] of the send, however many events arrive
    ///   while waiting.
    /// - `EIO` if the variable payload requested by the command has not been entirely
    ///   written to by its [`CommandToGsp::init_variable_payload`] method.
    ///
    /// Error codes returned by the command and reply initializers are propagated as-is.
    pub(crate) fn send_command<M>(&self, bar: Bar0<'_>, command: M) -> Result<M::Reply>
    where
        M: CommandToGsp,
        M::Reply: MessageFromGsp,
        Error: From<M::InitError>,
        Error: From<<M::Reply as MessageFromGsp>::InitError>,
    {
        let mut inner = self.inner.lock();
        let expected_seq = inner.send_command(bar, command)?;

        inner.await_msg(bar, Some(expected_seq))
    }

    /// Sends `command` to the GSP without waiting for a reply.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if space does not become available within the timeout.
    /// - `EIO` if the variable payload requested by the command has not been entirely
    ///   written to by its [`CommandToGsp::init_variable_payload`] method.
    ///
    /// Error codes returned by the command initializers are propagated as-is.
    #[expect(dead_code)]
    pub(crate) fn send_command_no_wait<M>(&self, bar: Bar0<'_>, command: M) -> Result
    where
        M: CommandToGsp<Reply = NoReply>,
        Error: From<M::InitError>,
    {
        self.inner.lock().send_command(bar, command).map(|_| ())
    }

    /// Receives one GMC element from the GSP and passes its command id, the `max_resp_or_status`
    /// field, and the raw payload slices to `handler`.
    ///
    /// This method may sleep while waiting. The [`CmdqInner`] mutex stays locked across the wait
    /// and across the `handler` call, so `handler` must not call back into this [`Cmdq`].
    ///
    /// See [`CmdqInner::receive_gmc_and_dispatch`] for return values, queue state, and errors.
    pub(crate) fn receive_gmc_and_dispatch<R>(
        &self,
        bar: Bar0<'_>,
        timeout: Delta,
        handler: impl FnOnce(u32, u32, &[u8], &[u8]) -> (Option<R>, QueuePointers),
    ) -> Result<Option<R>> {
        self.inner
            .lock()
            .receive_gmc_and_dispatch(bar, timeout, handler)
    }

    /// Sends a GMC API command to the GSP without waiting for its response.
    ///
    /// A caller that expects a response reads it with [`Self::receive_gmc_and_dispatch`], which
    /// lets it handle the events GSP-RM interleaves before the response arrives.
    ///
    /// # Errors
    ///
    /// - `EMSGSIZE` if the command exceeds the maximum queue element size.
    /// - `ETIMEDOUT` if space does not become available within the timeout.
    /// - `EIO` if the command header is not properly aligned.
    pub(crate) fn send_gmc_no_wait(
        &self,
        bar: Bar0<'_>,
        command_id: u32,
        payload: &[u8],
        max_response_size: u32,
    ) -> Result {
        self.inner
            .lock()
            .send_gmc(bar, command_id, payload, max_response_size)
    }

    /// Waits for an unsolicited GSP event of type `M`, consuming any other event that arrives
    /// first.
    ///
    /// The event answers no command, so it is matched on its function code alone.
    ///
    /// The queue is locked for the whole wait, for up to [`Self::RECEIVE_TIMEOUT`], so a
    /// concurrent command cannot consume the awaited event.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if the event does not arrive within [`Self::RECEIVE_TIMEOUT`] of the call,
    ///   however many other events arrive while waiting.
    /// - `EIO` if the queue is poisoned, or if a message fails framing or MCTP magic validation.
    ///
    /// Error codes returned by [`MessageFromGsp::read`] are propagated as-is.
    #[expect(dead_code)]
    pub(crate) fn await_msg<M: MessageFromGsp>(&self, bar: Bar0<'_>) -> Result<M>
    where
        // This allows all error types, including `Infallible`, to be used for `M::InitError`.
        Error: From<M::InitError>,
    {
        self.inner.lock().await_msg(bar, None)
    }

    /// Drains every message currently pending in the GSP-to-CPU queue.
    ///
    /// Consumes every message the GSP has already posted, logging the ones [`Self::await_msg`]
    /// would log, and returns without waiting for more.
    ///
    /// # Errors
    ///
    /// Propagates a receive error, in particular the `EIO` of a queue poisoned by corrupt framing.
    pub(crate) fn drain(&self, bar: Bar0<'_>) -> Result {
        self.inner.lock().drain(bar)
    }
}

/// Inner mutex protected state of [`Cmdq`].
struct CmdqInner {
    /// Device this command queue belongs to.
    dev: ARef<device::Device>,
    /// Next RPC sequence number. The GSP echoes it in a command's reply, which lets
    /// [`CmdqInner::receive_msg`] match that reply to the awaiting command. Advances once per
    /// logical command, so every continuation record of one command carries the same number.
    rpc_seq: u32,
    /// Numbers async sends in the debug log, which is the only place it appears.
    tx_async_seq: u32,
    /// Numbers GSP-initiated events in the debug log. The GSP leaves the RPC sequence unset on
    /// those messages, so the driver numbers them itself.
    rx_event_seq: u32,
    /// Set once a message fails framing or MCTP magic validation. Such a message has no
    /// trustworthy length, so the queue cannot advance past it and every later receive fails.
    ///
    /// A [`Cell`], so [`Self::wait_for_msg`] can set it through a shared borrow.
    poisoned: Cell<bool>,
    /// Memory area shared with the GSP for communicating commands and messages.
    gsp_mem: DmaGspMem,
}

impl CmdqInner {
    /// Timeout for waiting for space on the command queue.
    const ALLOCATE_TIMEOUT: Delta = Delta::from_secs(1);

    /// Sends `command` to the GSP, without splitting it.
    ///
    /// # Errors
    ///
    /// - `EMSGSIZE` if the command exceeds the maximum queue element size.
    /// - `ETIMEDOUT` if space does not become available within the timeout.
    /// - `EIO` if the variable payload requested by the command has not been entirely
    ///   written to by its [`CommandToGsp::init_variable_payload`] method.
    ///
    /// Error codes returned by the command initializers are propagated as-is.
    fn send_single_command<M>(&mut self, bar: Bar0<'_>, command: M, rpc_seq: u32) -> Result
    where
        M: CommandToGsp,
        // This allows all error types, including `Infallible`, to be used for `M::InitError`.
        Error: From<M::InitError>,
    {
        let size_in_bytes = command.size();
        let dst = self
            .gsp_mem
            .allocate_command(bar, size_in_bytes, Self::ALLOCATE_TIMEOUT)?;

        // Extract area for the command itself. The GSP message header and the command header
        // together are guaranteed to fit entirely into a single page, so it's ok to only look
        // at `dst.contents.0` here.
        let (cmd, payload_1) = M::Command::from_bytes_mut_prefix(dst.contents.0).ok_or(EIO)?;

        // Fill the header and command in-place.
        let msg_element = GspMsgElement::init(rpc_seq, size_in_bytes, M::FUNCTION);
        // SAFETY: `msg_header` and `cmd` are valid references, and not touched if the initializer
        // fails.
        unsafe {
            pin_init::raw_try_init(core::ptr::from_mut(dst.header), msg_element)?;
            pin_init::raw_try_init(core::ptr::from_mut(cmd), command.init())?;
        }

        // Fill the variable-length payload, which may be empty.
        let mut sbuffer = SBufferIter::new_writer([&mut payload_1[..], &mut dst.contents.1[..]]);
        command.init_variable_payload(&mut sbuffer)?;

        if !sbuffer.is_empty() {
            return Err(EIO);
        }
        drop(sbuffer);

        if M::IS_ASYNC {
            dev_dbg!(
                &self.dev,
                "GSP RPC: async send: seq# {}, function={:?}, length=0x{:x}\n",
                self.tx_async_seq,
                M::FUNCTION,
                dst.header.length(),
            );
            self.tx_async_seq = self.tx_async_seq.wrapping_add(1);
        } else {
            dev_dbg!(
                &self.dev,
                "GSP RPC: send: seq# {}, function={:?}, length=0x{:x}\n",
                rpc_seq,
                M::FUNCTION,
                dst.header.length(),
            );
        }

        // All set - update the write pointer and inform the GSP of the new command.
        let elem_count = dst.header.element_count();
        DmaGspMem::advance_cpu_write_ptr_v2(bar, elem_count);

        Ok(())
    }

    /// Sends `command` to the GSP and returns the RPC sequence number assigned to it.
    ///
    /// The command may be split into multiple messages if it is large. The GSP echoes the
    /// sequence number in the reply, so a caller passes it to [`Self::receive_msg`] to match the
    /// reply to this command.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if space does not become available within the timeout.
    /// - `EIO` if the variable payload requested by the command has not been entirely
    ///   written to by its [`CommandToGsp::init_variable_payload`] method.
    ///
    /// Error codes returned by the command initializers are propagated as-is.
    fn send_command<M>(&mut self, bar: Bar0<'_>, command: M) -> Result<u32>
    where
        M: CommandToGsp,
        Error: From<M::InitError>,
    {
        let rpc_seq = self.rpc_seq;
        self.rpc_seq = self.rpc_seq.wrapping_add(1);

        match SplitState::new(command)? {
            SplitState::Single(command) => self.send_single_command(bar, command, rpc_seq)?,
            SplitState::Split(command, mut continuations) => {
                self.send_single_command(bar, command, rpc_seq)?;

                while let Some(continuation) = continuations.next() {
                    // Turbofish needed because the compiler cannot infer M here.
                    self.send_single_command::<ContinuationRecord<'_>>(bar, continuation, rpc_seq)?;
                }
            }
        }

        Ok(rpc_seq)
    }

    /// Marks the queue unusable and returns the error every later receive fails with.
    ///
    /// `reason` names the inconsistency, and is logged.
    fn poison(&self, reason: fmt::Arguments<'_>) -> Error {
        dev_err!(&self.dev, "GSP RPC: receive: queue poisoned: {}\n", reason);
        self.poisoned.set(true);

        EIO
    }

    /// Sends a GMC API command to the GSP.
    ///
    /// `payload` is the data that follows the [`super::fw::GmcApiHeader`] on the wire, and
    /// `max_response_size` bounds the response GSP-RM may send.
    ///
    /// The command carries the next RPC sequence number, which the GSP echoes in its response.
    /// The number is consumed whether or not the send succeeds.
    ///
    /// # Errors
    ///
    /// - `EMSGSIZE` if the command exceeds the maximum queue element size.
    /// - `ETIMEDOUT` if space does not become available within the timeout.
    /// - `EIO` if the command header is not properly aligned.
    fn send_gmc(
        &mut self,
        bar: Bar0<'_>,
        command_id: u32,
        payload: &[u8],
        max_response_size: u32,
    ) -> Result {
        let rpc_seq = self.rpc_seq;
        self.rpc_seq = self.rpc_seq.wrapping_add(1);

        let dst = self.gsp_mem.allocate_command::<GspGmcMsgElement>(
            bar,
            payload.len(),
            Self::ALLOCATE_TIMEOUT,
        )?;

        let msg_element = GspGmcMsgElement::init(
            command_id,
            u64::from(rpc_seq),
            payload.len(),
            max_response_size,
        );
        // SAFETY: `dst.header` points to a valid, writable `GspGmcMsgElement` region.
        unsafe {
            msg_element.__init(core::ptr::from_mut(dst.header))?;
        }

        SBufferIter::new_writer([&mut dst.contents.0[..], &mut dst.contents.1[..]])
            .write_all(payload)?;

        dev_dbg!(
            &self.dev,
            "GSP GMC: send: seq# {}, command_id=0x{:x}, length=0x{:x}\n",
            rpc_seq,
            command_id,
            dst.header.length(),
        );

        let elem_count = dst.header.element_count();
        DmaGspMem::advance_cpu_write_ptr_v2(bar, elem_count);

        Ok(())
    }

    /// Wait for a message to become available on the message queue.
    ///
    /// This works purely at the transport layer and does not interpret or validate the message
    /// beyond the advertised length in its [`GspMsgElement`].
    ///
    /// This method returns:
    ///
    /// - A reference to the [`GspMsgElement`] of the message,
    /// - Two byte slices with the contents of the message. The second slice is empty unless the
    ///   message loops across the message queue.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if `timeout` has elapsed before any message becomes available.
    /// - `EIO` if the framing or the MCTP magic is invalid, or the queue was already poisoned by
    ///   an earlier such failure. Both poison the queue, so every later receive on it fails too.
    fn wait_for_msg(&self, bar: Bar0<'_>, timeout: Delta) -> Result<GspMessage<'_>> {
        if self.poisoned.get() {
            return Err(EIO);
        }

        // Wait for a message to arrive from the GSP.
        let (slice_1, slice_2) = read_poll_timeout(
            || Ok(self.gsp_mem.driver_read_area_v2(bar)),
            |driver_area| !driver_area.0.is_empty(),
            Delta::from_millis(1),
            timeout,
        )
        .map(|(slice_1, slice_2)| (slice_1.as_flattened(), slice_2.as_flattened()))?;

        // Extract the `GspMsgElement`.
        let Some((header, slice_1)) = GspMsgElement::from_bytes_prefix(slice_1) else {
            return Err(self.poison(fmt!(
                "read area of {} bytes is shorter than a message header",
                slice_1.len()
            )));
        };

        let payload_length = header.payload_length();

        // Check that the driver read area is large enough for the message.
        if slice_1.len() + slice_2.len() < payload_length {
            return Err(self.poison(fmt!(
                "message advertises {} payload bytes but only {} are readable",
                payload_length,
                slice_1.len() + slice_2.len()
            )));
        }

        // Cut the message slices down to the actual length of the message.
        let (slice_1, slice_2) = if slice_1.len() > payload_length {
            // PANIC: we checked above that `slice_1` is at least as long as `payload_length`.
            (slice_1.split_at(payload_length).0, &slice_2[0..0])
        } else {
            (
                slice_1,
                // PANIC: we checked above that `slice_1.len() + slice_2.len()` is at least as
                // large as `payload_length`.
                slice_2.split_at(payload_length - slice_1.len()).0,
            )
        };

        if !header.has_valid_magic() {
            return Err(self.poison(fmt!(
                "message with sequence {} has a bad MCTP magic",
                header.sequence()
            )));
        }

        Ok(GspMessage {
            header,
            contents: (slice_1, slice_2),
        })
    }

    /// Writes the classified receive debug line for a decoded GSP message.
    ///
    /// Events print [`Self::rx_event_seq`]. Command replies print `seq`. An unrecognized function
    /// code prints nothing here.
    fn log_received(&self, function: Result<MsgFunction, u32>, seq: u32, length: usize) {
        match function {
            Ok(f) if f.is_event() => {
                dev_dbg!(
                    &self.dev,
                    "GSP RPC: async received: seq# {}, function={:?}, length=0x{:x}\n",
                    self.rx_event_seq,
                    f,
                    length,
                );
            }
            Ok(f) => {
                dev_dbg!(
                    &self.dev,
                    "GSP RPC: response received: seq# {}, function={:?}, length=0x{:x}\n",
                    seq,
                    f,
                    length,
                );
            }
            Err(_) => {}
        }
    }

    /// Advances [`Self::rx_event_seq`] after a GSP-initiated event has been consumed.
    fn advance_rx_event_seq(&mut self, function: Result<MsgFunction, u32>) {
        if matches!(function, Ok(f) if f.is_event()) {
            self.rx_event_seq = self.rx_event_seq.wrapping_add(1);
        }
    }

    /// Receive a message from the GSP.
    ///
    /// The expected message type is specified using the `M` generic parameter. A message whose
    /// function code matches is decoded and returned. Any other message, recognized or not, goes
    /// to [`Self::log_event`], and `ENOMSG` is returned.
    ///
    /// With `expected_seq` set, the message must carry that RPC sequence number too. A message
    /// with the expected function code and a different sequence is a stale reply to a command
    /// that already timed out, so it is logged and dropped rather than classified as an event.
    ///
    /// The read pointer is always advanced past the message, regardless of whether it matched.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if `timeout` has elapsed before any message becomes available.
    /// - `EIO` if the queue is poisoned or the message fails framing or MCTP magic validation
    ///   (see [`Self::wait_for_msg`]), or if the matched message is too short for `M::Message`.
    /// - `ENOMSG` if the message was not the awaited reply.
    ///
    /// Error codes returned by [`MessageFromGsp::read`] are propagated as-is.
    fn receive_msg<M: MessageFromGsp>(
        &mut self,
        bar: Bar0<'_>,
        timeout: Delta,
        expected_seq: Option<u32>,
    ) -> Result<M>
    where
        // This allows all error types, including `Infallible`, to be used for `M::InitError`.
        Error: From<M::InitError>,
    {
        let message = self.wait_for_msg(bar, timeout)?;
        let function = message.header.function();
        let seq = message.header.sequence();
        let length = message.header.length();
        let func_matches = matches!(function, Ok(f) if f == M::FUNCTION);
        let matched = func_matches && expected_seq.is_none_or(|expected| seq == expected);

        self.log_received(function, seq, length);

        // Every path must advance the read pointer past this message, including a failed decode.
        let result = if matched {
            match M::Message::from_bytes_prefix(message.contents.0) {
                Some((cmd, contents_1)) => {
                    let mut sbuffer = SBufferIter::new_reader([contents_1, message.contents.1]);

                    M::read(cmd, &mut sbuffer)
                        .map_err(|e| e.into())
                        .inspect(|_| {
                            if !sbuffer.is_empty() {
                                dev_warn!(
                                    &self.dev,
                                    "GSP message {:?} has unprocessed data\n",
                                    M::FUNCTION
                                );
                            }
                        })
                }
                None => {
                    dev_warn!(&self.dev, "GSP message {:?} too short\n", M::FUNCTION);
                    Err(EIO)
                }
            }
        } else {
            if func_matches {
                dev_warn!(
                    &self.dev,
                    "GSP RPC: dropping stale {:?} reply (seq {}, awaiting {:?})\n",
                    M::FUNCTION,
                    seq,
                    expected_seq,
                );
            } else {
                self.log_event(function, seq);
            }

            Err(ENOMSG)
        };

        // Advance the read pointer past this message.
        DmaGspMem::advance_cpu_read_ptr_v2(bar, u32::try_from(length.div_ceil(GSP_PAGE_SIZE))?);

        self.advance_rx_event_seq(function);

        result
    }

    /// Receives a message of type `M`, waiting up to [`Cmdq::RECEIVE_TIMEOUT`] from the call.
    ///
    /// Any other message that arrives first goes to [`Self::log_event`] and does not extend the
    /// deadline. `expected_seq` narrows the match as [`Self::receive_msg`] describes.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if no message of type `M` arrives before the deadline, however many other
    ///   messages arrive while waiting.
    /// - `EIO` if the queue is poisoned or a message fails framing or MCTP magic validation (see
    ///   [`Self::wait_for_msg`]).
    ///
    /// Error codes returned by [`MessageFromGsp::read`] are propagated as-is.
    fn await_msg<M: MessageFromGsp>(
        &mut self,
        bar: Bar0<'_>,
        expected_seq: Option<u32>,
    ) -> Result<M>
    where
        // This allows all error types, including `Infallible`, to be used for `M::InitError`.
        Error: From<M::InitError>,
    {
        let deadline = Instant::<Monotonic>::now() + Cmdq::RECEIVE_TIMEOUT;
        loop {
            let remaining = deadline - Instant::<Monotonic>::now();
            if remaining.is_negative() {
                break Err(ETIMEDOUT);
            }
            match self.receive_msg::<M>(bar, remaining, expected_seq) {
                Ok(msg) => break Ok(msg),
                Err(ENOMSG) => continue,
                Err(e) => break Err(e),
            }
        }
    }

    /// Logs a message the GSP posted that no caller is waiting for.
    ///
    /// An error the GSP reports is logged at error level, and an unrecognized function code at
    /// warning level. Every other known function code produces no line of its own, and the
    /// receive trace in [`Self::log_received`] records its arrival.
    fn log_event(&self, function: Result<MsgFunction, u32>, seq: u32) {
        match function {
            Ok(MsgFunction::OsErrorLog) => {
                dev_err!(&self.dev, "GSP reported an OS error (seq {})\n", seq);
            }
            Ok(MsgFunction::RcTriggered) => {
                dev_err!(
                    &self.dev,
                    "GSP triggered robust-channel recovery (seq {})\n",
                    seq
                );
            }
            // GSP logs, libos prints, NoCat assertion records, and the other known event codes.
            // None of them requires action.
            Ok(_) => {}
            Err(raw) => {
                dev_warn!(
                    &self.dev,
                    "unknown GSP message function {:#x} (seq {})\n",
                    raw,
                    seq
                );
            }
        }
    }

    /// Drains all messages currently pending in the GSP-to-CPU queue.
    ///
    /// Reads whatever the GSP has already posted and stops once the queue is empty. No caller is
    /// waiting for a reply during a drain, so every message goes to [`Self::log_event`].
    ///
    /// # Errors
    ///
    /// Returns the receive error that stopped the drain, in particular the `EIO` of a queue
    /// poisoned by corrupt framing (see [`Self::wait_for_msg`]).
    fn drain(&mut self, bar: Bar0<'_>) -> Result {
        while !self.gsp_mem.driver_read_area_v2(bar).0.is_empty() {
            // A message is available, so this returns without waiting.
            let msg = self.wait_for_msg(bar, Delta::ZERO)?;
            let function = msg.header.function();
            let seq = msg.header.sequence();
            let length = msg.header.length();

            self.log_received(function, seq, length);

            let pages = u32::try_from(length.div_ceil(GSP_PAGE_SIZE)).map_err(|_| {
                dev_err!(&self.dev, "GSP drain: message length overflow\n");
                EIO
            })?;

            DmaGspMem::advance_cpu_read_ptr_v2(bar, pages);
            self.advance_rx_event_seq(function);
            self.log_event(function, seq);
        }

        Ok(())
    }

    /// Wait for a GMC message to become available on the message queue.
    ///
    /// This is the GMC counterpart to [`Self::wait_for_msg`] and reads the same queue. Like that
    /// method it works purely at the transport layer, validating the MCTP framing and the
    /// advertised length and nothing else.
    ///
    /// Both element kinds open with a [`super::fw::QueueElementHeader`], so a caller that may
    /// see either must check the NVDM type before it reads the GMC header.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if `timeout` has elapsed before any message becomes available.
    /// - `EIO` if the framing is invalid, or the queue was already poisoned by an earlier such
    ///   failure. Either failure poisons the queue, so recovery requires a reset.
    fn wait_for_gmc_msg(&self, bar: Bar0<'_>, timeout: Delta) -> Result<GmcMessage<'_>> {
        if self.poisoned.get() {
            return Err(EIO);
        }

        let (slice_1, slice_2) = read_poll_timeout(
            || Ok(self.gsp_mem.driver_read_area_v2(bar)),
            |driver_area| !driver_area.0.is_empty(),
            Delta::from_millis(1),
            timeout,
        )
        .map(|(slice_1, slice_2)| (slice_1.as_flattened(), slice_2.as_flattened()))?;

        let Some((header, slice_1)) = GspGmcMsgElement::from_bytes_prefix(slice_1) else {
            self.poisoned.set(true);
            return Err(EIO);
        };

        if let Err(e) = header.validate_framing() {
            dev_err!(
                &self.dev,
                "GSP GMC: receive: bad MCTP framing, declared length {}\n",
                header.length(),
            );
            self.poisoned.set(true);
            return Err(e);
        }

        let payload_length = header.payload_length();

        // Check that the driver read area is large enough for the message.
        if slice_1.len() + slice_2.len() < payload_length {
            self.poisoned.set(true);
            return Err(EIO);
        }

        // Cut the message slices down to the actual length of the message.
        let (slice_1, slice_2) = if slice_1.len() > payload_length {
            // PANIC: we checked above that `slice_1` is at least as long as `payload_length`.
            (slice_1.split_at(payload_length).0, &slice_2[0..0])
        } else {
            (
                slice_1,
                // PANIC: we checked above that `slice_1.len() + slice_2.len()` is at least as
                // large as `payload_length`.
                slice_2.split_at(payload_length - slice_1.len()).0,
            )
        };

        Ok(GmcMessage {
            header,
            contents: (slice_1, slice_2),
        })
    }

    /// Receive the next GMC event from the GSP and dispatch it through a handler.
    ///
    /// The handler receives the GMC command id, the raw payload slices that follow the
    /// [`super::fw::GmcApiHeader`] (two because the ring may wrap), and that header's
    /// `max_resp_or_status` field, which only a handler that knows what it asked for can read.
    /// It returns `None` for an element it does not handle, paired with the [`QueuePointers`]
    /// state it left behind.
    ///
    /// Returns `Ok(None)` when nothing claimed the element, either because it is not a GMC
    /// element or because the handler declined it. Either way the element is consumed: the read
    /// pointer moves past it, or is written back past it when the handler reset the GSP.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if `timeout` has elapsed before any message becomes available.
    /// - `EIO` if the queue is poisoned or the element fails framing validation (see
    ///   [`Self::wait_for_gmc_msg`]).
    fn receive_gmc_and_dispatch<R>(
        &mut self,
        bar: Bar0<'_>,
        timeout: Delta,
        handler: impl FnOnce(u32, u32, &[u8], &[u8]) -> (Option<R>, QueuePointers),
    ) -> Result<Option<R>> {
        let message = self.wait_for_gmc_msg(bar, timeout)?;
        let header = message.header;
        let length = header.length();

        // A handler that resets the GSP zeroes both of these, and the values they hold now are
        // the ones the driver has to put back.
        let cpu_write_ptr = DmaGspMem::cpu_write_ptr_v2(bar);
        let cpu_read_ptr = DmaGspMem::cpu_read_ptr_v2(bar);

        let (result, queue_pointers) = if !header.is_gmc_api() {
            dev_warn!(&self.dev, "GSP GMC: dropping non-GMC queue element\n");
            (None, QueuePointers::Unchanged)
        } else if num::u32_as_usize(header.gmc.size) != header.payload_length() {
            // GSP-RM sends the element as the GMC header plus `size` bytes, so the two lengths
            // describe the same payload and a handler cannot tell which one to believe.
            dev_err!(
                &self.dev,
                "GSP GMC: payload is {} bytes, transport declares {}\n",
                header.gmc.size,
                header.payload_length(),
            );
            (None, QueuePointers::Unchanged)
        } else {
            let command_id = header.gmc.command_id();

            dev_dbg!(
                &self.dev,
                "GSP GMC: event: seq# {}, command_id=0x{:x}, length=0x{:x}\n",
                header.gmc.sequence,
                command_id,
                length,
            );

            handler(
                command_id,
                header.gmc.max_resp_or_status,
                message.contents.0,
                message.contents.1,
            )
        };

        let pages = u32::try_from(length.div_ceil(GSP_PAGE_SIZE))?;

        match queue_pointers {
            QueuePointers::Unchanged => DmaGspMem::advance_cpu_read_ptr_v2(bar, pages),
            // The registers read zero now, so a read-modify-write would restart the driver's
            // side of the ring at zero while GSP-RM carries on from where it stopped. Put the
            // captured values back instead, with this element counted as consumed.
            QueuePointers::Reset => {
                DmaGspMem::restore_cpu_ptrs_v2(bar, cpu_write_ptr, cpu_read_ptr.wrapping_add(pages))
            }
        }

        Ok(result)
    }
}
