// SPDX-License-Identifier: GPL-2.0

mod continuation;

use core::{
    cell::Cell,
    mem, //
};

use kernel::{
    device,
    dma::{
        Coherent,
        CoherentBox,
        DmaAddress, //
    },
    fmt,
    io::{
        io_project,
        poll::read_poll_timeout,
        Io, //
    },
    new_mutex,
    prelude::*,
    ptr,
    sync::{
        barrier::{
            dma_mb,
            Full, //
        },
        Mutex, //
    },
    time::{
        Delta,
        Instant,
        Monotonic, //
    },
    transmute::{
        AsBytes,
        FromBytes, //
    },
};

use continuation::{
    ContinuationRecord,
    SplitState, //
};

use pin_init::pin_init_scope;

use crate::{
    driver::Bar0,
    gsp::{
        fw::{
            GspGmcMsgElement,
            GspMsgElement,
            MsgFunction,
            MsgqTxHeader,
            QueueElementHeader,
            GSP_MSG_QUEUE_ELEMENT_SIZE_MAX, //
        },
        PteArray,
        GSP_PAGE_SHIFT,
        GSP_PAGE_SIZE, //
    },
    mctp::NvdmType,
    num,
    sbuffer::SBufferIter, //
};

use super::regs;

/// Marker type representing the absence of a reply for a command. Commands using this as their
/// reply type are sent using [`Cmdq::send_command_no_wait`].
pub(crate) struct NoReply;

/// Trait implemented by types representing a command to send to the GSP.
///
/// The main purpose of this trait is to provide [`Cmdq`] with the information it needs to send
/// a given command.
///
/// [`CommandToGsp::init`] in particular is responsible for initializing the command directly
/// into the space reserved for it in the command queue buffer.
///
/// Some commands may be followed by a variable-length payload. For these, the
/// [`CommandToGsp::variable_payload_len`] and [`CommandToGsp::init_variable_payload`] need to be
/// defined as well.
pub(crate) trait CommandToGsp {
    /// Function identifying this command to the GSP.
    const FUNCTION: MsgFunction;

    /// Type generated by [`CommandToGsp::init`], to be written into the command queue buffer.
    type Command: FromBytes + AsBytes;

    /// Type of the reply expected from the GSP, or [`NoReply`] for commands that don't
    /// have a reply.
    type Reply;

    /// Error type returned by [`CommandToGsp::init`].
    type InitError;

    /// In-place command initializer responsible for filling the command in the command queue
    /// buffer.
    fn init(&self) -> impl Init<Self::Command, Self::InitError>;

    /// Size of the variable-length payload following the command structure generated by
    /// [`CommandToGsp::init`].
    ///
    /// Most commands don't have a variable-length payload, so this is zero by default.
    fn variable_payload_len(&self) -> usize {
        0
    }

    /// Method initializing the variable-length payload.
    ///
    /// The command buffer is circular, which means that we may need to jump back to its beginning
    /// while in the middle of a command. For this reason, the variable-length payload is
    /// initialized using a [`SBufferIter`].
    ///
    /// This method will receive a buffer of the length returned by
    /// [`CommandToGsp::variable_payload_len`], and must write every single byte of it. Leaving
    /// unwritten space will lead to an error.
    ///
    /// Most commands don't have a variable-length payload, so this does nothing by default.
    fn init_variable_payload(
        &self,
        _dst: &mut SBufferIter<core::array::IntoIter<&mut [u8], 2>>,
    ) -> Result {
        Ok(())
    }

    /// Total size of the command, its variable-length payload included, without the headers that
    /// open the queue element.
    fn size(&self) -> usize {
        size_of::<Self::Command>() + self.variable_payload_len()
    }
}

/// Trait representing messages received from the GSP.
///
/// A reply that [`Cmdq::send_command`] waits for, or an event that [`Cmdq::await_msg`] waits for.
/// The receiver matches a message's function code against [`Self::FUNCTION`] and decodes the
/// message with [`Self::read`].
pub(crate) trait MessageFromGsp: Sized {
    /// Function identifying this message from the GSP.
    const FUNCTION: MsgFunction;

    /// Error type returned by [`MessageFromGsp::read`].
    type InitError;

    /// Type containing the raw message to be read from the message queue.
    type Message: FromBytes;

    /// Method reading the message from the message queue and returning it.
    ///
    /// From a `Self::Message` and a [`SBufferIter`], constructs an instance of `Self` and returns
    /// it.
    fn read(
        msg: &Self::Message,
        sbuffer: &mut SBufferIter<core::array::IntoIter<&[u8], 2>>,
    ) -> Result<Self, Self::InitError>;
}

/// Number of GSP pages making the [`Msgq`].
pub(crate) const MSGQ_NUM_PAGES: u32 = 0x3f;

/// Circular buffer of a [`Msgq`].
///
/// This area of memory is to be shared between the driver and the GSP to exchange commands or
/// messages.
#[repr(C, align(0x1000))]
#[derive(Debug)]
struct MsgqData {
    data: [[u8; GSP_PAGE_SIZE]; num::u32_as_usize(MSGQ_NUM_PAGES)],
}

// Annoyingly we are forced to use a literal to specify the alignment of
// `MsgqData`, so check that it corresponds to the actual GSP page size here.
static_assert!(align_of::<MsgqData>() == GSP_PAGE_SIZE);

/// Unidirectional message queue.
///
/// Contains the data for a message queue, that either the driver or GSP writes to.
///
/// The queue pointers are in BAR0 registers, so `tx` carries the queue's geometry alone. `msgq`
/// is aligned to [`GSP_PAGE_SIZE`], and the bytes between the two are zero padding.
#[repr(C)]
// The firmware headers declare no struct for this layout.
struct Msgq {
    /// The msgq TX header, which describes the queue to the GSP.
    tx: MsgqTxHeader,
    /// The message queue proper.
    msgq: MsgqData,
}

/// Structure shared between the driver and the GSP and containing the command and message queues.
#[repr(C)]
struct GspMem {
    /// Self-mapping page table entries.
    ptes: PteArray<{ Self::PTE_ARRAY_SIZE }>,
    /// CPU queue: the driver writes commands here, and the GSP reads them.
    ///
    /// This member is read-only for the GSP.
    cpuq: Msgq,
    /// GSP queue: the GSP writes messages here, and the driver reads them.
    ///
    /// This member is read-only for the driver.
    gspq: Msgq,
}

impl GspMem {
    const PTE_ARRAY_SIZE: usize = GSP_PAGE_SIZE / size_of::<u64>();
}

// SAFETY: These structs don't meet the no-padding requirements of AsBytes but
// that is not a problem because they are not used outside the kernel.
unsafe impl AsBytes for GspMem {}

// SAFETY: These structs don't meet the no-padding requirements of FromBytes but
// that is not a problem because they are not used outside the kernel.
unsafe impl FromBytes for GspMem {}

/// Wrapper around [`GspMem`] to share it with the GPU using a [`Coherent`].
///
/// This provides the low-level functionality to communicate with the GSP, including allocation of
/// queue space to write messages to and management of read/write pointers.
///
/// This is shared with the GSP, with clear ownership rules regarding the command queues:
///
/// * The driver owns (i.e. can write to) the part of the CPU message queue between the CPU write
///   pointer and the GSP read pointer. This region is returned by [`Self::driver_write_area`].
/// * The driver owns (i.e. can read from) the part of the GSP message queue between the CPU read
///   pointer and the GSP write pointer. This region is returned by [`Self::driver_read_area`].
///
/// Each pointer counts elements without wrapping at the ring size: a ring is empty when its two
/// pointers are equal and full when they differ by the ring size. A GSP reset zeroes all four
/// pointer registers, so the driver keeps its own two pointers here and writes them out. It also
/// keeps the last value that it read of each GSP pointer, and uses that value while the register
/// reads as zero.
struct DmaGspMem<'a> {
    /// The queues, mapped for the GSP.
    mem: Coherent<'a, GspMem>,
    /// MMIO mapping of PCI BAR0, for the queue pointer registers.
    bar: Bar0<'a>,
    /// Number of elements that the driver has written to the command queue, published to the GSP
    /// through `NV_PGSP_QUEUE_HEAD`.
    cpu_write_ptr: u32,
    /// Number of elements that the driver has consumed from the message queue, published to the
    /// GSP through `NV_PGSP_MSGQ_TAIL`.
    cpu_read_ptr: u32,
    /// The GSP's count of consumed commands, as last read from `NV_PGSP_QUEUE_TAIL`.
    last_gsp_read_ptr: Cell<u32>,
    /// The GSP's count of posted messages, as last read from `NV_PGSP_MSGQ_HEAD`.
    last_gsp_write_ptr: Cell<u32>,
}

impl<'a> DmaGspMem<'a> {
    /// Allocate a new instance and map it for `dev`.
    fn new(dev: &'a device::Device<device::Bound>, bar: Bar0<'a>) -> Result<Self> {
        const MSGQ_SIZE: u32 = num::usize_into_u32::<{ size_of::<Msgq>() }>();
        const MSG_SIZE: u32 = num::usize_into_u32::<GSP_PAGE_SIZE>();
        const ENTRY_OFF: u32 = num::usize_into_u32::<{ mem::offset_of!(Msgq, msgq) }>();

        let mut gsp_mem = CoherentBox::<'_, GspMem>::zeroed(dev, GFP_KERNEL)?;
        gsp_mem.cpuq.tx = MsgqTxHeader::new(MSGQ_SIZE, MSG_SIZE, MSGQ_NUM_PAGES, ENTRY_OFF);

        let gsp_mem: Coherent<'_, _> = gsp_mem.into();
        PteArray::init(io_project!(gsp_mem, .ptes), gsp_mem.dma_address())?;

        Ok(Self {
            mem: gsp_mem,
            bar,
            cpu_write_ptr: 0,
            cpu_read_ptr: 0,
            last_gsp_read_ptr: Cell::new(0),
            last_gsp_write_ptr: Cell::new(0),
        })
    }

    /// Returns the region of the CPU message queue that the driver may write to.
    ///
    /// The ring wraps, so the region comes as two slices, and the second is empty unless the
    /// region crosses the end of the ring.
    fn driver_write_area(&mut self) -> (&mut [[u8; GSP_PAGE_SIZE]], &mut [[u8; GSP_PAGE_SIZE]]) {
        let avail = num::u32_as_usize(self.free_slots());
        let w_slot = num::u32_as_usize(self.cpu_write_ptr % MSGQ_NUM_PAGES);

        // Pointer to the first entry of the CPU message queue.
        let data = ptr::project!(mut self.mem.as_mut_ptr(), .cpuq.msgq.data[build: 0]);

        // SAFETY:
        // - `data` points to the `MSGQ_NUM_PAGES` initialized entries of the CPU message queue.
        // - The returned slices cover the `avail` free slots from the write pointer on, which the
        //   GSP does not read until `advance_cpu_write_ptr` publishes them.
        // - `split_at_mut` gives two non-overlapping halves, and the `&mut self` borrow lasts as
        //   long as the returned slices, so that no other call hands out the same region while
        //   they live.
        let data =
            unsafe { core::slice::from_raw_parts_mut(data, num::u32_as_usize(MSGQ_NUM_PAGES)) };
        let (before_w, after_w) = data.split_at_mut(w_slot);

        let in_after = avail.min(after_w.len());
        let in_before = avail - in_after;
        (&mut after_w[..in_after], &mut before_w[..in_before])
    }

    /// Returns the number of command queue slots that the driver may still write: the ring size
    /// minus the elements that the GSP has not consumed.
    fn free_slots(&self) -> u32 {
        let used = self.cpu_write_ptr.wrapping_sub(self.gsp_read_ptr());

        MSGQ_NUM_PAGES.saturating_sub(used)
    }

    /// Returns the number of bytes that the driver can still write to the command queue.
    fn driver_write_area_size(&self) -> usize {
        num::u32_as_usize(self.free_slots()) * GSP_PAGE_SIZE
    }

    /// Returns `true` if the GSP has posted a message that the driver has not consumed.
    fn has_unread_message(&self) -> bool {
        self.gsp_write_ptr() != self.cpu_read_ptr
    }

    /// Returns the region of the GSP message queue that the driver may read, as two slices
    /// because the ring wraps.
    fn driver_read_area(&self) -> (&[[u8; GSP_PAGE_SIZE]], &[[u8; GSP_PAGE_SIZE]]) {
        let avail = num::u32_as_usize(self.gsp_write_ptr().wrapping_sub(self.cpu_read_ptr));
        let r_slot = num::u32_as_usize(self.cpu_read_ptr % MSGQ_NUM_PAGES);

        // Pointer to the first entry of the GSP message queue.
        let data = ptr::project!(self.mem.as_ptr(), .gspq.msgq.data[build: 0]);

        // SAFETY:
        // - `data` points to the `MSGQ_NUM_PAGES` initialized entries of the GSP message queue.
        // - The returned slices cover the `avail` slots that the GSP has already written. The GSP
        //   does not write them again until `advance_cpu_read_ptr` releases them.
        let data = unsafe { core::slice::from_raw_parts(data, num::u32_as_usize(MSGQ_NUM_PAGES)) };
        let (before_r, after_r) = data.split_at(r_slot);

        let in_after = avail.min(after_r.len());
        let in_before = avail - in_after;
        (&after_r[..in_after], &before_r[..in_before])
    }

    /// Allocates a region on the command queue that is large enough to send a command of `size`
    /// bytes, waiting for space to become available based on the provided timeout.
    ///
    /// This returns a [`GspCommand`] ready to be written to by the caller.
    ///
    /// # Errors
    ///
    /// - `EMSGSIZE` if the command is larger than [`GSP_MSG_QUEUE_ELEMENT_SIZE_MAX`].
    /// - `ETIMEDOUT` if space does not become available within the timeout.
    /// - `EIO` if the first free slot is too short for the headers of type `H`, or misaligned for
    ///   them.
    fn allocate_command<H: FromBytes + AsBytes>(
        &mut self,
        size: usize,
        timeout: Delta,
    ) -> Result<GspCommand<'_, H>> {
        if size_of::<H>() + size > GSP_MSG_QUEUE_ELEMENT_SIZE_MAX {
            return Err(EMSGSIZE);
        }
        read_poll_timeout(
            || Ok(self.driver_write_area_size()),
            |available_bytes| *available_bytes >= size_of::<H>() + size,
            Delta::from_micros(1),
            timeout,
        )?;

        // Get the current writable area as an array of bytes.
        let (slice_1, slice_2) = {
            let (slice_1, slice_2) = self.driver_write_area();

            (slice_1.as_flattened_mut(), slice_2.as_flattened_mut())
        };

        let (header, slice_1) = H::from_bytes_mut_prefix(slice_1).ok_or(EIO)?;

        // Create the contents area.
        let (slice_1, slice_2) = if slice_1.len() > size {
            // Contents fits entirely in `slice_1`.
            (&mut slice_1[..size], &mut slice_2[0..0])
        } else {
            // Need all of `slice_1` and some of `slice_2`.
            let slice_2_len = size - slice_1.len();
            (slice_1, &mut slice_2[..slice_2_len])
        };

        Ok(GspCommand {
            header,
            contents: (slice_1, slice_2),
        })
    }

    /// Returns the GSP's count of posted messages.
    fn gsp_write_ptr(&self) -> u32 {
        // ORDERING: `readl` ends in a read barrier, which orders this read before the data reads
        // that follow it.
        let ptr = *self.bar.read(regs::NV_PGSP_MSGQ_HEAD).address();

        // A zeroed register is a GSP reset, not a count. No new element is readable until GSP-RM
        // posts a message and writes the register back.
        if ptr.wrapping_sub(self.cpu_read_ptr) > MSGQ_NUM_PAGES {
            return self.last_gsp_write_ptr.get();
        }
        self.last_gsp_write_ptr.set(ptr);

        ptr
    }

    /// Returns the GSP's count of consumed commands.
    fn gsp_read_ptr(&self) -> u32 {
        let ptr = *self.bar.read(regs::NV_PGSP_QUEUE_TAIL).address();

        // ORDERING: the data writes that follow must not pass this read. `readl` orders only the
        // reads that follow it, so the writes need a full barrier.
        dma_mb(Full);

        // A zeroed register is a GSP reset, not a count. This returns the last count that it read
        // until GSP-RM consumes a command and writes the register back. That count undercounts the
        // free space at worst.
        if self.cpu_write_ptr.wrapping_sub(ptr) > MSGQ_NUM_PAGES {
            return self.last_gsp_read_ptr.get();
        }
        self.last_gsp_read_ptr.set(ptr);

        ptr
    }

    /// Releases `elem_count` more elements of the message queue to the GSP.
    fn advance_cpu_read_ptr(&mut self, elem_count: u32) {
        self.cpu_read_ptr = self.cpu_read_ptr.wrapping_add(elem_count);

        // ORDERING: the data reads must complete before this write releases the slots to the GSP.
        // `writel` orders only the writes before it, so the reads need a full barrier.
        dma_mb(Full);

        self.bar
            .write_reg(regs::NV_PGSP_MSGQ_TAIL::zeroed().with_address(self.cpu_read_ptr));
    }

    /// Publishes `elem_count` more elements of the command queue to the GSP.
    ///
    /// The write to `NV_PGSP_QUEUE_HEAD` that publishes them also interrupts the GSP.
    fn advance_cpu_write_ptr(&mut self, elem_count: u32) {
        self.cpu_write_ptr = self.cpu_write_ptr.wrapping_add(elem_count);

        // ORDERING: `writel` begins with a write barrier, which orders the data writes before this
        // register write.
        self.bar
            .write_reg(regs::NV_PGSP_QUEUE_HEAD::zeroed().with_address(self.cpu_write_ptr));
    }
}

/// A command ready to be sent on the command queue.
///
/// `H` is the type of the headers that open the element, such as [`GspMsgElement`] for an RM RPC.
///
/// This is the type returned by [`DmaGspMem::allocate_command`].
struct GspCommand<'a, H> {
    // Writable reference to the header of the command.
    header: &'a mut H,
    // Writable slices to the contents of the command. The second slice is zero unless the command
    // loops over the command queue.
    contents: (&'a mut [u8], &'a mut [u8]),
}

/// An RPC message ready to be processed from the message queue.
///
/// This is the message that [`QueueElement::Rpc`] carries.
struct GspMessage<'a> {
    // Reference to the header of the message.
    header: &'a GspMsgElement,
    // Slices to the contents of the message. The second slice is zero unless the message loops
    // over the message queue.
    contents: (&'a [u8], &'a [u8]),
}

/// A GMC (GPU Management Controller) API message ready to be processed from the message queue.
///
/// This is the message that [`QueueElement::Gmc`] carries.
struct GmcMessage<'a> {
    // The queue element header and the GMC API header that open the element.
    header: &'a GspGmcMsgElement,
    // Slices to the payload that follows the GMC API header. The second slice is empty unless the
    // payload wraps around the end of the message queue.
    contents: (&'a [u8], &'a [u8]),
}

/// A queue element that has passed validation, decoded as an RPC message or as a GMC API message.
///
/// The queue element header holds an MCTP (Management Component Transport Protocol) header and an
/// NVDM (NVIDIA vendor-defined message) header. The NVDM type selects between the two kinds of
/// message.
///
/// This is the type returned by [`CmdqInner::wait_for_element`].
enum QueueElement<'a> {
    /// An RM RPC message.
    Rpc(GspMessage<'a>),
    /// A GMC API message.
    Gmc(GmcMessage<'a>),
}

impl QueueElement<'_> {
    /// Returns the number of queue slots that the element occupies.
    fn element_count(&self) -> u32 {
        match self {
            Self::Rpc(message) => message.header.element_count(),
            Self::Gmc(message) => message.header.element_count(),
        }
    }
}

/// The headers that open a queue element of one kind of message: the queue element header, then
/// the RPC header or the GMC API header.
trait MessageHeaders: FromBytes {
    /// Name of the kind of message, for the log line written when an element of this kind poisons
    /// the queue.
    const KIND: &'static str;

    /// Returns the length of the payload that follows the message header, or `None` if the queue
    /// element header declares a message shorter than the message header.
    fn payload_length(&self) -> Option<usize>;
}

impl MessageHeaders for GspMsgElement {
    const KIND: &'static str = "RPC";

    fn payload_length(&self) -> Option<usize> {
        GspMsgElement::payload_length(self)
    }
}

impl MessageHeaders for GspGmcMsgElement {
    const KIND: &'static str = "GMC";

    fn payload_length(&self) -> Option<usize> {
        GspGmcMsgElement::payload_length(self)
    }
}

/// GSP command queue.
///
/// Provides the ability to send commands and receive messages from the GSP using a shared memory
/// area.
#[pin_data]
pub(crate) struct Cmdq<'cmdq> {
    /// Inner mutex-protected state.
    #[pin]
    inner: Mutex<CmdqInner<'cmdq>>,
    /// DMA address of the command queue's shared memory region.
    pub(super) dma_addr: DmaAddress,
}

impl<'cmdq> Cmdq<'cmdq> {
    /// Offset of the data after the PTEs.
    const POST_PTE_OFFSET: usize = core::mem::offset_of!(GspMem, cpuq);

    /// Offset of command queue ring buffer.
    pub(crate) const CMDQ_OFFSET: usize = core::mem::offset_of!(GspMem, cpuq)
        + core::mem::offset_of!(Msgq, msgq)
        - Self::POST_PTE_OFFSET;

    /// Offset of message queue ring buffer.
    pub(crate) const STATQ_OFFSET: usize = core::mem::offset_of!(GspMem, gspq)
        + core::mem::offset_of!(Msgq, msgq)
        - Self::POST_PTE_OFFSET;

    /// Number of page table entries for the GSP shared region.
    pub(crate) const NUM_PTES: usize = size_of::<GspMem>() >> GSP_PAGE_SHIFT;

    /// Default timeout for receiving a message from the GSP.
    pub(super) const RECEIVE_TIMEOUT: Delta = Delta::from_secs(5);

    /// Creates a new command queue for `dev`.
    pub(crate) fn new(
        dev: &'cmdq device::Device<device::Bound>,
        bar: Bar0<'cmdq>,
    ) -> impl PinInit<Self, Error> + 'cmdq {
        pin_init_scope(move || {
            let gsp_mem = DmaGspMem::new(dev, bar)?;

            Ok(try_pin_init!(Self {
                dma_addr: gsp_mem.mem.dma_address(),
                inner <- new_mutex!(CmdqInner {
                    dev,
                    gsp_mem,
                    rpc_seq: 0,
                    poisoned: Cell::new(false),
                }),
            }))
        })
    }

    /// Sends `command` to the GSP and waits for the reply.
    ///
    /// Events that arrive before the reply are logged and consumed.
    ///
    /// The queue is locked for the entire send+receive cycle to ensure that no other command can
    /// be interleaved.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if space does not become available to send the command, or if the reply does
    ///   not arrive within [`Self::RECEIVE_TIMEOUT`] of the send, however many events arrive
    ///   while waiting.
    /// - `EIO` if the variable payload requested by the command has not been entirely
    ///   written to by its [`CommandToGsp::init_variable_payload`] method.
    ///
    /// Error codes returned by the command and reply initializers are propagated as-is.
    #[expect(dead_code)]
    pub(crate) fn send_command<M>(&self, command: M) -> Result<M::Reply>
    where
        M: CommandToGsp,
        M::Reply: MessageFromGsp,
        Error: From<M::InitError>,
        Error: From<<M::Reply as MessageFromGsp>::InitError>,
    {
        let mut inner = self.inner.lock();
        let expected_seq = inner.send_command(command)?;

        inner.await_msg(Some(expected_seq))
    }

    /// Sends `command` to the GSP without waiting for a reply.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if space does not become available within the timeout.
    /// - `EIO` if the variable payload requested by the command has not been entirely
    ///   written to by its [`CommandToGsp::init_variable_payload`] method.
    ///
    /// Error codes returned by the command initializers are propagated as-is.
    #[expect(dead_code)]
    pub(crate) fn send_command_no_wait<M>(&self, command: M) -> Result
    where
        M: CommandToGsp<Reply = NoReply>,
        Error: From<M::InitError>,
    {
        self.inner.lock().send_command(command).map(|_| ())
    }

    /// Waits for the response to the GMC request with command id `command_id`, and passes every
    /// other GMC element that arrives first to `on_other`.
    ///
    /// This method may sleep while waiting. The queue mutex stays locked across the whole wait and
    /// across the `on_other` and `decode` calls, so neither may call back into this [`Cmdq`].
    ///
    /// See [`CmdqInner::await_gmc_response`] for the return value and the errors.
    pub(crate) fn await_gmc_response<R>(
        &self,
        command_id: u32,
        on_other: impl FnMut(&GspGmcMsgElement, &[u8], &[u8]) -> Result,
        decode: impl FnMut(&[u8], &[u8]) -> Result<R>,
    ) -> Result<R> {
        self.inner
            .lock()
            .await_gmc_response(command_id, on_other, decode)
    }

    /// Sends a GMC API request to the GSP without waiting for the response.
    ///
    /// # Errors
    ///
    /// Errors from [`DmaGspMem::allocate_command`] are propagated as-is.
    pub(crate) fn send_gmc_no_wait(
        &self,
        command_id: u32,
        payload: &[u8],
        max_response_size: u32,
    ) -> Result {
        self.inner
            .lock()
            .send_gmc(command_id, payload, max_response_size)
    }

    /// Waits for an unsolicited GSP event of type `M`. Events that arrive before it are logged and
    /// consumed.
    ///
    /// The event answers no command, so it is matched on its function code alone.
    ///
    /// The queue mutex is held for the whole wait, up to [`Self::RECEIVE_TIMEOUT`], so no other
    /// caller can send a command or consume an event meanwhile.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if the event does not arrive within [`Self::RECEIVE_TIMEOUT`] of the call,
    ///   however many other events arrive while waiting.
    /// - `EIO` if the queue is poisoned, or if a message fails framing validation.
    ///
    /// Error codes returned by [`MessageFromGsp::read`] are propagated as-is.
    #[expect(dead_code)]
    pub(crate) fn await_msg<M: MessageFromGsp>(&self) -> Result<M>
    where
        // This allows all error types, including `Infallible`, to be used for `M::InitError`.
        Error: From<M::InitError>,
    {
        self.inner.lock().await_msg(None)
    }

    /// Logs and consumes every element that the GSP has already posted, and returns without waiting
    /// for more.
    ///
    /// No caller is waiting for a reply while this holds the queue mutex, so every element is
    /// logged as an event. See "Draining the GSP-to-CPU queue" in
    /// `Documentation/gpu/nova/core/interrupts.rst`.
    ///
    /// # Errors
    ///
    /// `EIO` if the queue is poisoned, or if an element fails framing validation.
    pub(crate) fn drain(&self) -> Result {
        self.inner.lock().drain()
    }
}

/// Inner mutex protected state of [`Cmdq`].
struct CmdqInner<'a> {
    /// Device this command queue belongs to.
    dev: &'a device::Device,
    /// Next RPC sequence number, advanced once per command, however many messages the command is
    /// split into.
    rpc_seq: u32,
    /// Set once an element fails framing validation. Every later receive fails, because the bad
    /// element cannot be skipped. See "Draining the GSP-to-CPU queue" in
    /// `Documentation/gpu/nova/core/interrupts.rst`.
    ///
    /// A [`Cell`], because the receive path sets it through `&self`.
    poisoned: Cell<bool>,
    /// Memory area shared with the GSP for communicating commands and messages.
    gsp_mem: DmaGspMem<'a>,
}

impl CmdqInner<'_> {
    /// Timeout for waiting for space on the command queue.
    const ALLOCATE_TIMEOUT: Delta = Delta::from_secs(1);

    /// Sends `command` to the GSP, without splitting it.
    ///
    /// # Errors
    ///
    /// - `EMSGSIZE` if the command exceeds the maximum queue element size.
    /// - `ETIMEDOUT` if space does not become available within the timeout.
    /// - `EIO` if the variable payload requested by the command has not been entirely
    ///   written to by its [`CommandToGsp::init_variable_payload`] method.
    ///
    /// Error codes returned by the command initializers are propagated as-is.
    fn send_single_command<M>(&mut self, command: M, rpc_seq: u32) -> Result
    where
        M: CommandToGsp,
        // This allows all error types, including `Infallible`, to be used for `M::InitError`.
        Error: From<M::InitError>,
    {
        let size_in_bytes = command.size();
        let dst = self
            .gsp_mem
            .allocate_command(size_in_bytes, Self::ALLOCATE_TIMEOUT)?;

        // Extract area for the command itself. The GSP message header and the command header
        // together are guaranteed to fit entirely into a single page, so it's ok to only look
        // at `dst.contents.0` here.
        let (cmd, payload_1) = M::Command::from_bytes_mut_prefix(dst.contents.0).ok_or(EIO)?;

        // Fill the header and command in-place.
        let msg_element = GspMsgElement::init(rpc_seq, size_in_bytes, M::FUNCTION);
        // SAFETY: `msg_header` and `cmd` are valid references, and not touched if the initializer
        // fails.
        unsafe {
            pin_init::raw_try_init(core::ptr::from_mut(dst.header), msg_element)?;
            pin_init::raw_try_init(core::ptr::from_mut(cmd), command.init())?;
        }

        // Fill the variable-length payload, which may be empty.
        let mut sbuffer = SBufferIter::new_writer([&mut payload_1[..], &mut dst.contents.1[..]]);
        command.init_variable_payload(&mut sbuffer)?;

        if !sbuffer.is_empty() {
            return Err(EIO);
        }
        drop(sbuffer);

        dev_dbg!(
            &self.dev,
            "GSP RPC: send: seq# {}, function={:?}, length=0x{:x}\n",
            rpc_seq,
            M::FUNCTION,
            dst.header.length(),
        );

        // All set - update the write pointer and inform the GSP of the new command.
        let elem_count = dst.header.element_count();
        self.gsp_mem.advance_cpu_write_ptr(elem_count);

        Ok(())
    }

    /// Sends `command` to the GSP and returns the RPC sequence number assigned to it.
    ///
    /// The command may be split into multiple messages if it is large. GSP-RM copies the
    /// sequence number into its reply.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if space does not become available within the timeout.
    /// - `EIO` if the variable payload requested by the command has not been entirely
    ///   written to by its [`CommandToGsp::init_variable_payload`] method.
    ///
    /// Error codes returned by the command initializers are propagated as-is.
    fn send_command<M>(&mut self, command: M) -> Result<u32>
    where
        M: CommandToGsp,
        Error: From<M::InitError>,
    {
        let rpc_seq = self.rpc_seq;
        self.rpc_seq = self.rpc_seq.wrapping_add(1);

        match SplitState::new(command)? {
            SplitState::Single(command) => self.send_single_command(command, rpc_seq)?,
            SplitState::Split(command, mut continuations) => {
                self.send_single_command(command, rpc_seq)?;

                while let Some(continuation) = continuations.next() {
                    // Turbofish needed because the compiler cannot infer M here.
                    self.send_single_command::<ContinuationRecord<'_>>(continuation, rpc_seq)?;
                }
            }
        }

        Ok(rpc_seq)
    }

    /// Logs `reason`, poisons the queue, and returns `EIO` for the caller to propagate.
    fn poison(&self, reason: fmt::Arguments<'_>) -> Error {
        dev_err!(&self.dev, "GSP receive: queue poisoned: {}\n", reason);
        self.poisoned.set(true);

        EIO
    }

    /// Sends a GMC API request to the GSP.
    ///
    /// `payload` follows the GMC API header in the element, and `max_response_size` is the largest
    /// response that the caller accepts. The request carries the next RPC sequence number, which
    /// GSP-RM copies into its response. The number is consumed even if the send fails.
    ///
    /// # Errors
    ///
    /// Errors from [`DmaGspMem::allocate_command`] are propagated as-is.
    fn send_gmc(&mut self, command_id: u32, payload: &[u8], max_response_size: u32) -> Result {
        let rpc_seq = self.rpc_seq;
        self.rpc_seq = self.rpc_seq.wrapping_add(1);

        let dst = self
            .gsp_mem
            .allocate_command::<GspGmcMsgElement>(payload.len(), Self::ALLOCATE_TIMEOUT)?;

        let msg_element = GspGmcMsgElement::init(
            command_id,
            u64::from(rpc_seq),
            payload.len(),
            max_response_size,
        );
        // SAFETY: `dst.header` is a valid reference, and not written if the initializer fails.
        unsafe {
            pin_init::raw_try_init(core::ptr::from_mut(dst.header), msg_element)?;
        }

        SBufferIter::new_writer([&mut dst.contents.0[..], &mut dst.contents.1[..]])
            .write_all(payload)?;

        dev_dbg!(
            &self.dev,
            "GSP GMC: send: seq# {}, command_id=0x{:x}, length=0x{:x}\n",
            rpc_seq,
            command_id,
            dst.header.length(),
        );

        let elem_count = dst.header.element_count();
        self.gsp_mem.advance_cpu_write_ptr(elem_count);

        Ok(())
    }

    /// Receives an element from the GSP.
    ///
    /// [`Self::match_rpc_reply`] decodes an RPC message as the awaited reply of type `M`, or logs
    /// it. `expected_seq` narrows the match. A GMC message is logged as unclaimed.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if `timeout` has elapsed before any element becomes available.
    /// - `EIO` if the queue is poisoned or the element fails framing validation (see
    ///   [`Self::wait_for_element`]), or if the matched message is too short for `M::Message`.
    /// - `ENOMSG` if the element is not the awaited reply.
    ///
    /// Error codes returned by [`MessageFromGsp::read`] are propagated as-is.
    fn receive_msg<M: MessageFromGsp>(
        &mut self,
        timeout: Delta,
        expected_seq: Option<u32>,
    ) -> Result<M>
    where
        // This allows all error types, including `Infallible`, to be used for `M::InitError`.
        Error: From<M::InitError>,
    {
        self.consume_element(timeout, |this, element| match element {
            QueueElement::Gmc(message) => {
                this.log_gmc_event(message.header);

                Err(ENOMSG)
            }
            QueueElement::Rpc(message) => this.match_rpc_reply::<M>(&message, expected_seq),
        })
    }

    /// Decodes `message` as the awaited reply of type `M`, or logs it.
    ///
    /// A message whose function code is `M::FUNCTION` is decoded and returned. Any other message
    /// is logged as an event.
    ///
    /// With `expected_seq` set, the message must carry that RPC sequence number too. A message
    /// with the expected function code and a different sequence is a stale reply to a command
    /// that already timed out, so it is logged as stale rather than as an event.
    ///
    /// # Errors
    ///
    /// - `EIO` if the matched message is too short for `M::Message`.
    /// - `ENOMSG` if the message is not the awaited reply.
    ///
    /// Error codes returned by [`MessageFromGsp::read`] are propagated as-is.
    fn match_rpc_reply<M: MessageFromGsp>(
        &self,
        message: &GspMessage<'_>,
        expected_seq: Option<u32>,
    ) -> Result<M>
    where
        // This allows all error types, including `Infallible`, to be used for `M::InitError`.
        Error: From<M::InitError>,
    {
        let function = message.header.function();
        let seq = message.header.sequence();
        let func_matches = matches!(function, Ok(f) if f == M::FUNCTION);
        let matched = func_matches && expected_seq.is_none_or(|expected| seq == expected);

        if matched {
            match M::Message::from_bytes_prefix(message.contents.0) {
                Some((cmd, contents_1)) => {
                    let mut sbuffer = SBufferIter::new_reader([contents_1, message.contents.1]);

                    M::read(cmd, &mut sbuffer)
                        .map_err(|e| e.into())
                        .inspect(|_| {
                            if !sbuffer.is_empty() {
                                dev_warn!(
                                    &self.dev,
                                    "GSP message {:?} has unprocessed data\n",
                                    M::FUNCTION
                                );
                            }
                        })
                }
                None => {
                    dev_warn!(&self.dev, "GSP message {:?} too short\n", M::FUNCTION);
                    Err(EIO)
                }
            }
        } else {
            if func_matches {
                dev_warn!(
                    &self.dev,
                    "GSP RPC: dropping stale {:?} reply (seq {}, awaiting {:?})\n",
                    M::FUNCTION,
                    seq,
                    expected_seq,
                );
            } else {
                self.log_event(function, seq);
            }

            Err(ENOMSG)
        }
    }

    /// Receives a message of type `M`, waiting up to [`Cmdq::RECEIVE_TIMEOUT`] from the call.
    ///
    /// Any other element that arrives first is logged and does not extend the deadline.
    /// `expected_seq` narrows the match as [`Self::match_rpc_reply`] describes.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if no message of type `M` arrives before the deadline, however many other
    ///   elements arrive while waiting.
    /// - `EIO` if the queue is poisoned or an element fails framing validation (see
    ///   [`Self::wait_for_element`]).
    ///
    /// Error codes returned by [`MessageFromGsp::read`] are propagated as-is.
    fn await_msg<M: MessageFromGsp>(&mut self, expected_seq: Option<u32>) -> Result<M>
    where
        // This allows all error types, including `Infallible`, to be used for `M::InitError`.
        Error: From<M::InitError>,
    {
        let deadline = Instant::<Monotonic>::now() + Cmdq::RECEIVE_TIMEOUT;
        loop {
            let remaining = deadline - Instant::<Monotonic>::now();
            if remaining.is_negative() {
                break Err(ETIMEDOUT);
            }
            match self.receive_msg::<M>(remaining, expected_seq) {
                Ok(msg) => break Ok(msg),
                Err(ENOMSG) => continue,
                Err(e) => break Err(e),
            }
        }
    }

    /// Logs an event, meaning an RPC message that no caller is waiting for.
    ///
    /// An OS error or robust-channel record is logged at error level and an unknown function code
    /// at warning level. Every other event is recorded only by the receive trace in
    /// [`Self::consume_element`].
    fn log_event(&self, function: Result<MsgFunction, u32>, seq: u32) {
        match function {
            Ok(MsgFunction::OsErrorLog) => {
                dev_err!(&self.dev, "GSP reported an OS error (seq {})\n", seq);
            }
            Ok(MsgFunction::RcTriggered) => {
                dev_err!(
                    &self.dev,
                    "GSP triggered robust-channel recovery (seq {})\n",
                    seq
                );
            }
            // Nothing to do for the remaining known function codes.
            Ok(_) => {}
            Err(raw) => {
                dev_warn!(
                    &self.dev,
                    "unknown GSP message function {:#x} (seq {})\n",
                    raw,
                    seq
                );
            }
        }
    }

    /// Logs a GMC message that no caller is waiting for: a response to a request that has already
    /// timed out, or an event that arrives outside the boot sequence.
    fn log_gmc_event(&self, header: &GspGmcMsgElement) {
        dev_warn!(
            &self.dev,
            "GSP GMC: dropping unclaimed message (seq {}, command_id=0x{:x})\n",
            header.gmc.sequence,
            header.gmc.command_id(),
        );
    }

    /// Logs and consumes every element that the queue holds.
    ///
    /// # Errors
    ///
    /// `EIO` if the queue is poisoned or an element fails framing validation.
    fn drain(&mut self) -> Result {
        while self.gsp_mem.has_unread_message() {
            // An element is available, so this returns without waiting.
            self.consume_element(Delta::ZERO, |this, element| {
                match element {
                    QueueElement::Rpc(message) => {
                        this.log_event(message.header.function(), message.header.sequence());
                    }
                    QueueElement::Gmc(message) => this.log_gmc_event(message.header),
                }

                Ok(())
            })?;
        }

        Ok(())
    }

    /// Truncates the read area that follows the queue element header and the message header to
    /// the `payload_length` bytes of payload.
    ///
    /// # Errors
    ///
    /// - `EIO` if fewer bytes than that are readable, which poisons the queue.
    fn payload_slices<'a>(
        &self,
        slice_1: &'a [u8],
        slice_2: &'a [u8],
        payload_length: usize,
    ) -> Result<(&'a [u8], &'a [u8])> {
        if slice_1.len() + slice_2.len() < payload_length {
            return Err(self.poison(fmt!(
                "message advertises {} payload bytes but only {} are readable",
                payload_length,
                slice_1.len() + slice_2.len()
            )));
        }

        Ok(if slice_1.len() > payload_length {
            // PANIC: we checked above that `slice_1` is at least as long as `payload_length`.
            (slice_1.split_at(payload_length).0, &slice_2[0..0])
        } else {
            (
                slice_1,
                // PANIC: we checked above that `slice_1.len() + slice_2.len()` is at least as
                // large as `payload_length`.
                slice_2.split_at(payload_length - slice_1.len()).0,
            )
        })
    }

    /// Waits for the next queue element and decodes it as an RPC message or as a GMC API message.
    ///
    /// ```text
    ///     +------------------------------------+
    ///     | queue element header: magic, MCTP  |  validated
    ///     |   header, NVDM header, lengths     |
    ///     +------------------------------------+
    ///     | message header                     |  decoded as the RPC header or the GMC API
    ///     +------------------------------------+  header. The NVDM type selects between the two.
    ///     | payload                            |  truncated to the length that the queue
    ///     +------------------------------------+  element header declares
    /// ```
    ///
    /// The element stays at the queue head, and the payload slices point into it, so the read
    /// pointer must not advance until they are dropped.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if `timeout` has elapsed before any element becomes available.
    /// - `EIO` if the queue is already poisoned, or if the framing, the NVDM type or a declared
    ///   length is invalid, or if the GMC API header and the queue element header declare
    ///   different payload sizes. Each of these poisons the queue (see [`Self::poisoned`]).
    fn wait_for_element(&self, timeout: Delta) -> Result<QueueElement<'_>> {
        if self.poisoned.get() {
            return Err(EIO);
        }

        let (slice_1, slice_2) = read_poll_timeout(
            || Ok(self.gsp_mem.driver_read_area()),
            |driver_area| !driver_area.0.is_empty(),
            Delta::from_millis(1),
            timeout,
        )
        .map(|(slice_1, slice_2)| (slice_1.as_flattened(), slice_2.as_flattened()))?;

        let Some((element_header, _)) = QueueElementHeader::from_bytes_prefix(slice_1) else {
            return Err(self.poison(fmt!(
                "read area of {} bytes is shorter than a queue element header",
                slice_1.len()
            )));
        };

        if let Err(error) = element_header.validate() {
            return Err(self.poison(fmt!(
                "element has a bad queue element header ({:?}), declared length {}",
                error,
                element_header.element_len()
            )));
        }

        match element_header.nvdm_type() {
            Ok(NvdmType::RmRpc) => {
                let (header, contents) = self.split_element::<GspMsgElement>(slice_1, slice_2)?;

                Ok(QueueElement::Rpc(GspMessage { header, contents }))
            }
            Ok(NvdmType::GmcApi) => {
                let (header, contents) =
                    self.split_element::<GspGmcMsgElement>(slice_1, slice_2)?;

                // GSP-RM writes both sizes from the same payload, so a difference means that one
                // of the two headers is corrupt, and the driver cannot know which.
                let payload_length = contents.0.len() + contents.1.len();
                if payload_length != num::u32_as_usize(header.gmc.size) {
                    return Err(self.poison(fmt!(
                        "GMC seq# {}: GMC API header declares {} payload bytes, element header {}",
                        header.gmc.sequence,
                        header.gmc.size,
                        payload_length
                    )));
                }

                Ok(QueueElement::Gmc(GmcMessage { header, contents }))
            }
            Ok(nvdm_type) => Err(self.poison(fmt!(
                "element carries NVDM type {:?}, which the GSP queues do not use",
                nvdm_type
            ))),
            Err(_) => Err(self.poison(fmt!("element carries an unknown NVDM type"))),
        }
    }

    /// Splits the read area into the headers of type `H` that open the element and the payload
    /// slices that follow them.
    ///
    /// # Errors
    ///
    /// - `EIO` if the read area is shorter than the headers, if the queue element header declares
    ///   a message shorter than the message header, or if fewer payload bytes are readable than
    ///   declared. Each of these poisons the queue.
    fn split_element<'a, H: MessageHeaders>(
        &self,
        slice_1: &'a [u8],
        slice_2: &'a [u8],
    ) -> Result<(&'a H, (&'a [u8], &'a [u8]))> {
        let Some((header, slice_1)) = H::from_bytes_prefix(slice_1) else {
            return Err(self.poison(fmt!(
                "{} element: read area is shorter than the message header",
                H::KIND
            )));
        };

        let Some(payload_length) = header.payload_length() else {
            return Err(self.poison(fmt!(
                "{} element declares a message shorter than the message header",
                H::KIND
            )));
        };

        let contents = self.payload_slices(slice_1, slice_2, payload_length)?;

        Ok((header, contents))
    }

    /// Waits for the next queue element, passes it to `f`, and advances the read pointer past it.
    ///
    /// The read pointer advances whether `f` succeeds or fails, so that `f` is called once per
    /// element. The element and its payload slices are valid only inside `f`.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if `timeout` has elapsed before any element becomes available.
    /// - `EIO` if the queue is poisoned or the element is invalid, as [`Self::wait_for_element`]
    ///   describes.
    ///
    /// Errors from `f` are propagated as-is.
    fn consume_element<R>(
        &mut self,
        timeout: Delta,
        f: impl FnOnce(&Self, QueueElement<'_>) -> Result<R>,
    ) -> Result<R> {
        let element = self.wait_for_element(timeout)?;
        let element_count = element.element_count();

        match &element {
            QueueElement::Rpc(message) => dev_dbg!(
                &self.dev,
                "GSP RPC: receive: seq# {}, function={:?}, length=0x{:x}\n",
                message.header.sequence(),
                message.header.function(),
                message.header.length(),
            ),
            QueueElement::Gmc(message) => dev_dbg!(
                &self.dev,
                "GSP GMC: receive: seq# {}, command_id=0x{:x}, length=0x{:x}\n",
                message.header.gmc.sequence,
                message.header.gmc.command_id(),
                message.header.length(),
            ),
        }

        let result = f(self, element);

        self.gsp_mem.advance_cpu_read_ptr(element_count);

        result
    }

    /// Receives the next queue element and, if it is a GMC element, passes it to `handler`.
    ///
    /// `handler` receives the headers that open the element and the payload that follows the GMC
    /// API header, as two slices because the ring may wrap. An RPC element is logged as an event.
    ///
    /// Returns `Ok(None)` when `handler` declines the element or when the element is not a GMC
    /// element.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if no element arrives within `timeout`.
    /// - `EIO` if the queue is poisoned or the element is invalid, as
    ///   [`Self::wait_for_element`] describes.
    ///
    /// Errors from `handler` are propagated as-is.
    fn receive_gmc_and_dispatch<R>(
        &mut self,
        timeout: Delta,
        handler: impl FnOnce(&GspGmcMsgElement, &[u8], &[u8]) -> Result<Option<R>>,
    ) -> Result<Option<R>> {
        self.consume_element(timeout, |this, element| match element {
            QueueElement::Rpc(message) => {
                this.log_event(message.header.function(), message.header.sequence());

                Ok(None)
            }
            QueueElement::Gmc(message) => {
                handler(message.header, message.contents.0, message.contents.1)
            }
        })
    }

    /// Waits for the response to the GMC request with command id `command_id`, up to
    /// [`Cmdq::RECEIVE_TIMEOUT`] from the call.
    ///
    /// The response's payload is passed to `decode`, as two slices because the ring may wrap.
    /// Every other GMC element that arrives first is passed to `on_other` with the headers that
    /// open it and its payload slices, and an RPC element is logged as an event. Neither kind of
    /// element extends the deadline.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if the response does not arrive before the deadline, however many other
    ///   elements arrive while waiting.
    /// - `EIO` if the queue is poisoned or an element fails framing validation (see
    ///   [`Self::wait_for_element`]), or if the response carries a failure status.
    ///
    /// Errors from `on_other` and `decode` are propagated as-is.
    fn await_gmc_response<R>(
        &mut self,
        command_id: u32,
        mut on_other: impl FnMut(&GspGmcMsgElement, &[u8], &[u8]) -> Result,
        mut decode: impl FnMut(&[u8], &[u8]) -> Result<R>,
    ) -> Result<R> {
        let dev = self.dev;
        let deadline = Instant::<Monotonic>::now() + Cmdq::RECEIVE_TIMEOUT;
        loop {
            let remaining = deadline - Instant::<Monotonic>::now();
            if remaining.is_negative() {
                break Err(ETIMEDOUT);
            }

            let response =
                self.receive_gmc_and_dispatch(remaining, |header, payload_0, payload_1| {
                    if header.gmc.command_id() != command_id {
                        return on_other(header, payload_0, payload_1).map(|()| None);
                    }

                    let status = header.gmc.status();
                    if status != 0 {
                        dev_err!(
                            dev,
                            "GSP GMC: command 0x{:x} failed, status={:#x}\n",
                            command_id,
                            status
                        );
                        return Err(EIO);
                    }

                    decode(payload_0, payload_1).map(Some)
                })?;

            if let Some(response) = response {
                break Ok(response);
            }
        }
    }
}
