// SPDX-License-Identifier: GPL-2.0

mod continuation;

use core::{
    cell::Cell,
    mem,
    sync::atomic::{
        fence,
        Ordering, //
    },
};

use kernel::{
    device,
    dma::{
        Coherent,
        CoherentBox,
        DmaAddress, //
    },
    io::{
        io_project,
        poll::read_poll_timeout,
        Io, //
    },
    new_mutex,
    prelude::*,
    ptr,
    sync::{
        aref::ARef,
        Mutex, //
    },
    time::{
        Delta,
        Instant,
        Monotonic, //
    },
    transmute::{
        AsBytes,
        FromBytes, //
    },
};

use continuation::{
    ContinuationRecord,
    SplitState, //
};

use pin_init::pin_init_scope;

use crate::{
    driver::Bar0,
    gsp::{
        fw::{
            GspGmcMsgElement,
            GspMsgElement,
            MsgFunction,
            MsgqRxHeader,
            MsgqTxHeaderV2,
            GMCAPI_COMMAND_ID_MASK,
            GSP_MSG_QUEUE_ELEMENT_SIZE_MAX, //
        },
        PteArray,
        GSP_PAGE_SHIFT,
        GSP_PAGE_SIZE, //
    },
    num,
    sbuffer::SBufferIter, //
};

use super::regs;

/// Marker type representing the absence of a reply for a command. Commands using this as their
/// reply type are sent using [`Cmdq::send_command_no_wait`].
pub(crate) struct NoReply;

/// Trait implemented by types representing a command to send to the GSP.
///
/// The main purpose of this trait is to provide [`Cmdq`] with the information it needs to send
/// a given command.
///
/// [`CommandToGsp::init`] in particular is responsible for initializing the command directly
/// into the space reserved for it in the command queue buffer.
///
/// Some commands may be followed by a variable-length payload. For these, the
/// [`CommandToGsp::variable_payload_len`] and [`CommandToGsp::init_variable_payload`] need to be
/// defined as well.
pub(crate) trait CommandToGsp {
    /// Function identifying this command to the GSP.
    const FUNCTION: MsgFunction;

    /// Classifies the send-side debug log as an async send.
    ///
    /// Default is `false`. Set this only on commands that are sent without waiting for a reply. A
    /// [`NoReply`] continuation of a waited-for command stays `false`.
    const IS_ASYNC: bool = false;

    /// Type generated by [`CommandToGsp::init`], to be written into the command queue buffer.
    type Command: FromBytes + AsBytes;

    /// Type of the reply expected from the GSP, or [`NoReply`] for commands that don't
    /// have a reply.
    type Reply;

    /// Error type returned by [`CommandToGsp::init`].
    type InitError;

    /// In-place command initializer responsible for filling the command in the command queue
    /// buffer.
    fn init(&self) -> impl Init<Self::Command, Self::InitError>;

    /// Size of the variable-length payload following the command structure generated by
    /// [`CommandToGsp::init`].
    ///
    /// Most commands don't have a variable-length payload, so this is zero by default.
    fn variable_payload_len(&self) -> usize {
        0
    }

    /// Method initializing the variable-length payload.
    ///
    /// The command buffer is circular, which means that we may need to jump back to its beginning
    /// while in the middle of a command. For this reason, the variable-length payload is
    /// initialized using a [`SBufferIter`].
    ///
    /// This method will receive a buffer of the length returned by
    /// [`CommandToGsp::variable_payload_len`], and must write every single byte of it. Leaving
    /// unwritten space will lead to an error.
    ///
    /// Most commands don't have a variable-length payload, so this does nothing by default.
    fn init_variable_payload(
        &self,
        _dst: &mut SBufferIter<core::array::IntoIter<&mut [u8], 2>>,
    ) -> Result {
        Ok(())
    }

    /// Total size of the command (including its variable-length payload) without the
    /// [`GspMsgElement`] header.
    fn size(&self) -> usize {
        size_of::<Self::Command>() + self.variable_payload_len()
    }
}

/// Trait representing messages received from the GSP.
///
/// This trait tells [`Cmdq::receive_msg`] how it can receive a given type of message.
pub(crate) trait MessageFromGsp: Sized {
    /// Function identifying this message from the GSP.
    const FUNCTION: MsgFunction;

    /// Error type returned by [`MessageFromGsp::read`].
    type InitError;

    /// Type containing the raw message to be read from the message queue.
    type Message: FromBytes;

    /// Method reading the message from the message queue and returning it.
    ///
    /// From a `Self::Message` and a [`SBufferIter`], constructs an instance of `Self` and returns
    /// it.
    fn read(
        msg: &Self::Message,
        sbuffer: &mut SBufferIter<core::array::IntoIter<&[u8], 2>>,
    ) -> Result<Self, Self::InitError>;
}

/// Number of GSP pages making the [`Msgq`].
pub(crate) const MSGQ_NUM_PAGES: u32 = 0x3f;

/// Circular buffer of a [`Msgq`].
///
/// This area of memory is to be shared between the driver and the GSP to exchange commands or
/// messages.
#[repr(C, align(0x1000))]
#[derive(Debug)]
struct MsgqData {
    data: [[u8; GSP_PAGE_SIZE]; num::u32_as_usize(MSGQ_NUM_PAGES)],
}

// Annoyingly we are forced to use a literal to specify the alignment of
// `MsgqData`, so check that it corresponds to the actual GSP page size here.
static_assert!(align_of::<MsgqData>() == GSP_PAGE_SIZE);

/// Unidirectional message queue.
///
/// Contains the data for a message queue, that either the driver or GSP writes to.
///
/// Note that while the write pointer of `tx` corresponds to the `msgq` of the same instance, the
/// read pointer of `rx` actually refers to the `Msgq` owned by the other side.
/// This design ensures that only the driver or GSP ever writes to a given instance of this struct.
#[repr(C)]
// There is no struct defined for this in the open-gpu-kernel-source headers.
// Instead it is defined by code in `GspMsgQueuesInit()`.
struct Msgq {
    /// Header describing the queue geometry. Msgq v2 keeps the write pointer in BAR0 instead.
    tx: MsgqTxHeaderV2,
    /// Header that carried the read pointer under msgq v0. Msgq v2 keeps that pointer in BAR0
    /// and never writes this, but the GSP still expects the space.
    rx: MsgqRxHeader,
    /// The message queue proper.
    msgq: MsgqData,
}

/// Structure shared between the driver and the GSP and containing the command and message queues.
#[repr(C)]
struct GspMem {
    /// Self-mapping page table entries.
    ptes: PteArray<{ Self::PTE_ARRAY_SIZE }>,
    /// CPU queue: the driver writes commands here, and the GSP reads them. It also contains the
    /// write and read pointers that the CPU updates. This means that the read pointer here is an
    /// index into the GSP queue.
    ///
    /// This member is read-only for the GSP.
    cpuq: Msgq,
    /// GSP queue: the GSP writes messages here, and the driver reads them. It also contains the
    /// write and read pointers that the GSP updates. This means that the read pointer here is an
    /// index into the CPU queue.
    ///
    /// This member is read-only for the driver.
    gspq: Msgq,
}

impl GspMem {
    const PTE_ARRAY_SIZE: usize = GSP_PAGE_SIZE / size_of::<u64>();
}

// SAFETY: These structs don't meet the no-padding requirements of AsBytes but
// that is not a problem because they are not used outside the kernel.
unsafe impl AsBytes for GspMem {}

// SAFETY: These structs don't meet the no-padding requirements of FromBytes but
// that is not a problem because they are not used outside the kernel.
unsafe impl FromBytes for GspMem {}

/// Wrapper around [`GspMem`] to share it with the GPU using a [`Coherent`].
///
/// This provides the low-level functionality to communicate with the GSP, including allocation of
/// queue space to write messages to and management of read/write pointers.
///
/// This is shared with the GSP, with clear ownership rules regarding the command queues:
///
/// * The driver owns (i.e. can write to) the part of the CPU message queue between the CPU write
///   pointer and the GSP read pointer. This region is returned by [`Self::driver_write_area`].
/// * The driver owns (i.e. can read from) the part of the GSP message queue between the CPU read
///   pointer and the GSP write pointer. This region is returned by [`Self::driver_read_area`].
struct DmaGspMem(Coherent<GspMem>);

impl DmaGspMem {
    /// Allocate a new instance and map it for `dev`.
    fn new(dev: &device::Device<device::Bound>) -> Result<Self> {
        const MSGQ_SIZE: u32 = num::usize_into_u32::<{ size_of::<Msgq>() }>();
        const MSG_SIZE: u32 = num::usize_into_u32::<GSP_PAGE_SIZE>();
        const ENTRY_OFF: u32 = num::usize_into_u32::<{ mem::offset_of!(Msgq, msgq) }>();

        // Msgq v2 keeps all four ring pointers in BAR0, so the in-memory RX header is never
        // written and the TX header carries geometry only.
        let mut gsp_mem = CoherentBox::<GspMem>::zeroed(dev, GFP_KERNEL)?;
        gsp_mem.cpuq.tx = MsgqTxHeaderV2::new(MSGQ_SIZE, MSG_SIZE, MSGQ_NUM_PAGES, ENTRY_OFF);

        let gsp_mem: Coherent<_> = gsp_mem.into();
        PteArray::init(io_project!(gsp_mem, .ptes), gsp_mem.dma_address())?;

        Ok(Self(gsp_mem))
    }

    /// Allocates a region on the command queue that is large enough to send a command of `size`
    /// bytes, waiting for space to become available based on the provided timeout.
    ///
    /// The type parameter `H` selects the message element header, [`GspMsgElement`] for RM RPC.
    ///
    /// This returns a [`GspCommand`] ready to be written to by the caller.
    ///
    /// # Errors
    ///
    /// - `EMSGSIZE` if the command is larger than [`GSP_MSG_QUEUE_ELEMENT_SIZE_MAX`].
    /// - `ETIMEDOUT` if space does not become available within the timeout.
    /// - `EIO` if the command header is not properly aligned.
    fn allocate_command<H: FromBytes + AsBytes>(
        &mut self,
        bar: Bar0<'_>,
        size: usize,
        timeout: Delta,
    ) -> Result<GspCommand<'_, H>> {
        if size_of::<H>() + size > GSP_MSG_QUEUE_ELEMENT_SIZE_MAX {
            return Err(EMSGSIZE);
        }
        read_poll_timeout(
            || Ok(Self::driver_write_area_size_v2(bar)),
            |available_bytes| *available_bytes >= size_of::<H>() + size,
            Delta::from_micros(1),
            timeout,
        )?;

        // Get the current writable area as an array of bytes.
        let (slice_1, slice_2) = {
            let (slice_1, slice_2) = self.driver_write_area_v2(bar);

            (slice_1.as_flattened_mut(), slice_2.as_flattened_mut())
        };

        // Extract area for the message element header.
        let (header, slice_1) = H::from_bytes_mut_prefix(slice_1).ok_or(EIO)?;

        // Create the contents area.
        let (slice_1, slice_2) = if slice_1.len() > size {
            // Contents fits entirely in `slice_1`.
            (&mut slice_1[..size], &mut slice_2[0..0])
        } else {
            // Need all of `slice_1` and some of `slice_2`.
            let slice_2_len = size - slice_1.len();
            (slice_1, &mut slice_2[..slice_2_len])
        };

        Ok(GspCommand {
            header,
            contents: (slice_1, slice_2),
        })
    }
}

// Msgq v2 internals.
//
// Msgq v2 keeps the four ring pointers in BAR0 registers as monotonic `u32`
// counters that wrap on overflow. The slot index is `ptr % MSGQ_NUM_PAGES`
// only at the point of use, and the ring uses every slot (no "leave one
// empty" rule, since `head == tail` distinguishes empty from full).
//
// Register-to-role mapping for queue 0:
//
//     CPU TX write/doorbell:  NV_PGSP_QUEUE_HEAD
//     GSP TX read:            NV_PGSP_QUEUE_TAIL
//     GSP RX write:           NV_PGSP_MSGQ_HEAD
//     CPU RX read:            NV_PGSP_MSGQ_TAIL
//
// A GSP reset zeroes all four counters while the in-memory ring keeps its
// contents. Neither end restarts at zero: GSP-RM writes its own two back
// from its internal state when it resumes, and the driver writes back the
// two it owns (`restore_cpu_ptrs_v2`). Between the reset and GSP-RM's
// write-back the read pointer is ahead of the write pointer, which
// `driver_read_area_v2` reports as an empty ring.
//
// TODO: suspend/resume reset-recovery is not implemented. A power cycle
// loses the driver-side counters as well, so both ends have to be
// re-established rather than restored.
impl DmaGspMem {
    fn gsp_write_ptr_v2(bar: Bar0<'_>) -> u32 {
        *bar.read(regs::NV_PGSP_MSGQ_HEAD).address()
    }

    fn gsp_read_ptr_v2(bar: Bar0<'_>) -> u32 {
        *bar.read(regs::NV_PGSP_QUEUE_TAIL).address()
    }

    fn cpu_read_ptr_v2(bar: Bar0<'_>) -> u32 {
        *bar.read(regs::NV_PGSP_MSGQ_TAIL).address()
    }

    fn cpu_write_ptr_v2(bar: Bar0<'_>) -> u32 {
        *bar.read(regs::NV_PGSP_QUEUE_HEAD).address()
    }

    /// Writes back the two counters the driver owns, after a GSP reset has zeroed all four.
    ///
    /// GSP-RM restores `NV_PGSP_MSGQ_HEAD` and `NV_PGSP_QUEUE_TAIL` from its own state when it
    /// resumes, and continues counting from where it left off rather than from zero. The driver
    /// owns the other two and has to do the same, or the two ends address different slots.
    fn restore_cpu_ptrs_v2(bar: Bar0<'_>, write_ptr: u32, read_ptr: u32) {
        fence(Ordering::SeqCst);

        bar.write_reg(regs::NV_PGSP_MSGQ_TAIL::zeroed().with_address(read_ptr));
        bar.write_reg(regs::NV_PGSP_QUEUE_HEAD::zeroed().with_address(write_ptr));
    }

    fn advance_cpu_read_ptr_v2(bar: Bar0<'_>, count: u32) {
        let new_rptr = Self::cpu_read_ptr_v2(bar).wrapping_add(count);

        // Order all reads from the message data ahead of the read-pointer
        // update so the GSP cannot recycle the slots while we are still
        // looking at them.
        fence(Ordering::SeqCst);

        bar.write_reg(regs::NV_PGSP_MSGQ_TAIL::zeroed().with_address(new_rptr));
    }

    fn advance_cpu_write_ptr_v2(bar: Bar0<'_>, count: u32) {
        let new_wptr = Self::cpu_write_ptr_v2(bar).wrapping_add(count);

        // Order all writes to the message data ahead of the write-pointer
        // update. Writing the head register doubles as the GSP doorbell.
        fence(Ordering::SeqCst);

        bar.write_reg(regs::NV_PGSP_QUEUE_HEAD::zeroed().with_address(new_wptr));
    }

    /// Returns the region of the CPU message queue that the driver is currently allowed to write
    /// to.
    ///
    /// As the message queue is a circular buffer, the region may be discontiguous in memory. In
    /// that case the second slice will have a non-zero length.
    fn driver_write_area_v2(
        &mut self,
        bar: Bar0<'_>,
    ) -> (&mut [[u8; GSP_PAGE_SIZE]], &mut [[u8; GSP_PAGE_SIZE]]) {
        let raw_w = Self::cpu_write_ptr_v2(bar);
        let raw_r = Self::gsp_read_ptr_v2(bar);

        let used = raw_w.wrapping_sub(raw_r);
        let avail = num::u32_as_usize(MSGQ_NUM_PAGES.saturating_sub(used));
        let w_slot = num::u32_as_usize(raw_w % MSGQ_NUM_PAGES);

        // Pointer to the first entry of the CPU message queue.
        let data = ptr::project!(mut self.0.as_mut_ptr(), .cpuq.msgq.data[build: 0]);

        // SAFETY:
        // - `data` points to `MSGQ_NUM_PAGES` valid message queue entries.
        // - We will only access the driver-owned part of the shared memory.
        // - Per the safety statement of the function, no concurrent access will be performed.
        let data =
            unsafe { core::slice::from_raw_parts_mut(data, num::u32_as_usize(MSGQ_NUM_PAGES)) };
        let (before_w, after_w) = data.split_at_mut(w_slot);

        let in_after = avail.min(after_w.len());
        let in_before = avail - in_after;
        (&mut after_w[..in_after], &mut before_w[..in_before])
    }

    /// Returns the size, in bytes, of the region of the CPU message queue that the driver is
    /// currently allowed to write to.
    fn driver_write_area_size_v2(bar: Bar0<'_>) -> usize {
        let used = Self::cpu_write_ptr_v2(bar).wrapping_sub(Self::gsp_read_ptr_v2(bar));
        let slots = MSGQ_NUM_PAGES.saturating_sub(used);
        num::u32_as_usize(slots) * GSP_PAGE_SIZE
    }

    /// Returns the region of the GSP message queue that the driver is currently allowed to read
    /// from.
    ///
    /// As the message queue is a circular buffer, the region may be discontiguous in memory. In
    /// that case the second slice will have a non-zero length.
    fn driver_read_area_v2(
        &self,
        bar: Bar0<'_>,
    ) -> (&[[u8; GSP_PAGE_SIZE]], &[[u8; GSP_PAGE_SIZE]]) {
        let raw_w = Self::gsp_write_ptr_v2(bar);
        let raw_r = Self::cpu_read_ptr_v2(bar);

        // A difference wider than the ring means the GSP has been reset and has not yet written
        // its own counter back, so the read pointer is momentarily ahead of it. Report nothing
        // readable, which holds the callers in their poll until GSP-RM restores the real value.
        let pending = raw_w.wrapping_sub(raw_r);
        let avail = if pending > MSGQ_NUM_PAGES {
            0
        } else {
            num::u32_as_usize(pending)
        };
        let r_slot = num::u32_as_usize(raw_r % MSGQ_NUM_PAGES);

        // Pointer to the first entry of the GSP message queue.
        let data = ptr::project!(self.0.as_ptr(), .gspq.msgq.data[build: 0]);

        // SAFETY:
        // - `data` points to `MSGQ_NUM_PAGES` valid message queue entries.
        // - We will only access the driver-owned part of the shared memory.
        // - Per the safety statement of the function, no concurrent access will be performed.
        let data = unsafe { core::slice::from_raw_parts(data, num::u32_as_usize(MSGQ_NUM_PAGES)) };
        let (before_r, after_r) = data.split_at(r_slot);

        let in_after = avail.min(after_r.len());
        let in_before = avail - in_after;
        (&after_r[..in_after], &before_r[..in_before])
    }
}

/// A command ready to be sent on the command queue.
///
/// The type parameter `H` is the message element header type, [`GspMsgElement`] for RM RPC.
///
/// This is the type returned by [`DmaGspMem::allocate_command`].
struct GspCommand<'a, H = GspMsgElement> {
    // Writable reference to the header of the command.
    header: &'a mut H,
    // Writable slices to the contents of the command. The second slice is zero unless the command
    // loops over the command queue.
    contents: (&'a mut [u8], &'a mut [u8]),
}

/// A message ready to be processed from the message queue.
///
/// This is the type returned by [`CmdqInner::wait_for_msg`].
struct GspMessage<'a> {
    // Reference to the header of the message.
    header: &'a GspMsgElement,
    // Slices to the contents of the message. The second slice is zero unless the message loops
    // over the message queue.
    contents: (&'a [u8], &'a [u8]),
}

/// A GMC message ready to be processed from the message queue.
///
/// This is the type returned by [`CmdqInner::wait_for_gmc_msg`].
struct GmcMessage<'a> {
    // Reference to the header of the message.
    header: &'a GspGmcMsgElement,
    // Slices of the payload following the `GmcApiHeader`. The second slice is empty unless the
    // payload wraps around the end of the message queue.
    contents: (&'a [u8], &'a [u8]),
}

/// State of the msgq v2 pointer registers after a GMC dispatch handler has run.
///
/// Resetting the GSP falcon zeroes all four pointer registers, which leaves the read pointer
/// where consuming the current element would have put it. A handler reports which case applies
/// so that [`CmdqInner::receive_gmc_and_dispatch`] can tell whether the read pointer still needs
/// advancing.
#[derive(PartialEq, Eq)]
pub(crate) enum QueuePointers {
    /// The handler left the pointer registers alone.
    Unchanged,
    /// The handler reset the GSP, which zeroed the pointer registers.
    Reset,
}

/// Response from a GMC API command.
pub(crate) struct GmcResponse {
    /// The 24-bit GMC command identifier from the response (flags stripped).
    pub(crate) command: u32,
    /// Response status (`NV_STATUS` code). Zero means success.
    pub(crate) status: u32,
    /// Response payload copied out of the message queue.
    pub(crate) payload: KVec<u8>,
    /// Sequence number used to match this response to its request.
    sequence: u64,
}

/// GSP command queue.
///
/// Provides the ability to send commands and receive messages from the GSP using a shared memory
/// area.
#[pin_data]
pub(crate) struct Cmdq {
    /// Inner mutex-protected state.
    #[pin]
    inner: Mutex<CmdqInner>,
    /// DMA address of the command queue's shared memory region.
    pub(super) dma_addr: DmaAddress,
}

impl Cmdq {
    /// Offset of the data after the PTEs.
    const POST_PTE_OFFSET: usize = core::mem::offset_of!(GspMem, cpuq);

    /// Offset of command queue ring buffer.
    pub(crate) const CMDQ_OFFSET: usize = core::mem::offset_of!(GspMem, cpuq)
        + core::mem::offset_of!(Msgq, msgq)
        - Self::POST_PTE_OFFSET;

    /// Offset of message queue ring buffer.
    pub(crate) const STATQ_OFFSET: usize = core::mem::offset_of!(GspMem, gspq)
        + core::mem::offset_of!(Msgq, msgq)
        - Self::POST_PTE_OFFSET;

    /// Number of page table entries for the GSP shared region.
    pub(crate) const NUM_PTES: usize = size_of::<GspMem>() >> GSP_PAGE_SHIFT;

    /// Default timeout for receiving a message from the GSP.
    pub(super) const RECEIVE_TIMEOUT: Delta = Delta::from_secs(5);

    /// Creates a new command queue for `dev`.
    pub(crate) fn new(dev: &device::Device<device::Bound>) -> impl PinInit<Self, Error> + '_ {
        pin_init_scope(move || {
            let gsp_mem = DmaGspMem::new(dev)?;

            Ok(try_pin_init!(Self {
                dma_addr: gsp_mem.0.dma_address(),
                inner <- new_mutex!(CmdqInner {
                    dev: dev.into(),
                    gsp_mem,
                    rpc_seq: 0,
                    tx_async_seq: 0,
                    rx_event_seq: 0,
                    poisoned: Cell::new(false),
                }),
            }))
        })
    }

    /// Sends `command` to the GSP and waits for the reply.
    ///
    /// A message read while waiting that is not the reply goes to
    /// [`CmdqInner::dispatch_event`].
    ///
    /// The queue is locked for the entire send+receive cycle, so no other command can be
    /// interleaved.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if space does not become available to send the command, or if the reply does
    ///   not arrive within [`Self::RECEIVE_TIMEOUT`] of the send, however many events are
    ///   dispatched while waiting.
    /// - `EIO` if the variable payload requested by the command has not been entirely
    ///   written to by its [`CommandToGsp::init_variable_payload`] method.
    ///
    /// Error codes returned by the command and reply initializers are propagated as-is.
    pub(crate) fn send_command<M>(&self, bar: Bar0<'_>, command: M) -> Result<M::Reply>
    where
        M: CommandToGsp,
        M::Reply: MessageFromGsp,
        Error: From<M::InitError>,
        Error: From<<M::Reply as MessageFromGsp>::InitError>,
    {
        let mut inner = self.inner.lock();
        let expected_seq = inner.send_command(bar, command)?;

        let deadline = Instant::<Monotonic>::now() + Self::RECEIVE_TIMEOUT;
        loop {
            let remaining = deadline - Instant::<Monotonic>::now();
            if remaining.is_negative() {
                break Err(ETIMEDOUT);
            }
            match inner.receive_msg::<M::Reply>(bar, remaining, Some(expected_seq)) {
                Ok(reply) => break Ok(reply),
                Err(ERANGE) => continue,
                Err(e) => break Err(e),
            }
        }
    }

    /// Sends `command` to the GSP without waiting for a reply.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if space does not become available within the timeout.
    /// - `EIO` if the variable payload requested by the command has not been entirely
    ///   written to by its [`CommandToGsp::init_variable_payload`] method.
    ///
    /// Error codes returned by the command initializers are propagated as-is.
    #[expect(dead_code)]
    pub(crate) fn send_command_no_wait<M>(&self, bar: Bar0<'_>, command: M) -> Result
    where
        M: CommandToGsp<Reply = NoReply>,
        Error: From<M::InitError>,
    {
        self.inner.lock().send_command(bar, command).map(|_| ())
    }

    /// Receive a message from the GSP, matching on the function code alone.
    ///
    /// Returns `ERANGE` if the message that arrives is not of type `M`. See
    /// [`CmdqInner::receive_msg`].
    fn receive_msg<M: MessageFromGsp>(&self, bar: Bar0<'_>, timeout: Delta) -> Result<M>
    where
        // This allows all error types, including `Infallible`, to be used for `M::InitError`.
        Error: From<M::InitError>,
    {
        self.inner.lock().receive_msg(bar, timeout, None)
    }

    /// Receives one GMC element from the GSP and passes its command id, the `max_resp_or_status`
    /// field, and the raw payload slices to `handler`.
    ///
    /// This method may sleep while waiting. The [`CmdqInner`] mutex stays locked across the wait
    /// and across the `handler` call, so `handler` must not call back into this [`Cmdq`].
    ///
    /// See [`CmdqInner::receive_gmc_and_dispatch`] for return values, queue state, and errors.
    pub(crate) fn receive_gmc_and_dispatch<R>(
        &self,
        bar: Bar0<'_>,
        timeout: Delta,
        handler: impl FnOnce(u32, u32, u64, &[u8], &[u8]) -> (Option<R>, QueuePointers),
    ) -> Result<Option<R>> {
        self.inner
            .lock()
            .receive_gmc_and_dispatch(bar, timeout, handler)
    }

    /// Sends a GMC API command to the GSP without waiting for its response.
    ///
    /// A caller that expects a response reads it with [`Self::receive_gmc_and_dispatch`], which
    /// lets it handle the events GSP-RM interleaves before the response arrives.
    ///
    /// # Errors
    ///
    /// - `EMSGSIZE` if the command exceeds the maximum queue element size.
    /// - `ETIMEDOUT` if space does not become available within the timeout.
    /// - `EIO` if the command header is not properly aligned.
    pub(crate) fn send_gmc_no_wait(
        &self,
        bar: Bar0<'_>,
        command_id: u32,
        payload: &[u8],
        max_response_size: u32,
    ) -> Result {
        self.inner
            .lock()
            .send_gmc(bar, command_id, payload, max_response_size)
            .map(|_| ())
    }

    /// Sends a GMC API command and waits for its matching response.
    ///
    /// The queue stays locked for the complete transaction. A single deadline bounds all queue
    /// elements observed while waiting.
    pub(crate) fn send_gmc_and_receive(
        &self,
        bar: Bar0<'_>,
        command_id: u32,
        payload: &[u8],
        max_response_size: u32,
    ) -> Result<GmcResponse> {
        self.send_gmc_and_receive_timeout(
            bar,
            command_id,
            payload,
            max_response_size,
            Self::RECEIVE_TIMEOUT,
        )
    }

    /// Sends a GMC API command and waits up to `timeout` for its matching response.
    pub(crate) fn send_gmc_and_receive_timeout(
        &self,
        bar: Bar0<'_>,
        command_id: u32,
        payload: &[u8],
        max_response_size: u32,
        timeout: Delta,
    ) -> Result<GmcResponse> {
        let mut inner = self.inner.lock();
        let expected_sequence = inner.send_gmc(bar, command_id, payload, max_response_size)?;
        let expected_command = command_id & GMCAPI_COMMAND_ID_MASK;
        let dev = inner.dev.clone();

        let deadline = Instant::<Monotonic>::now() + timeout;
        loop {
            let remaining = deadline - Instant::<Monotonic>::now();
            if remaining.is_negative() {
                return Err(ETIMEDOUT);
            }

            let response = match inner.receive_gmc_and_dispatch(
                bar,
                remaining,
                |received_command, status, sequence, payload_0, payload_1| {
                    let response: Result<GmcResponse> = (|| {
                        let mut payload = KVec::with_capacity(
                            payload_0.len().checked_add(payload_1.len()).ok_or(EOVERFLOW)?,
                            GFP_KERNEL,
                        )?;
                        payload.extend_from_slice(payload_0, GFP_KERNEL)?;
                        payload.extend_from_slice(payload_1, GFP_KERNEL)?;
                        Ok(GmcResponse {
                            command: received_command,
                            status,
                            payload,
                            sequence,
                        })
                    })();

                    (Some(response), QueuePointers::Unchanged)
                },
            ) {
                Ok(response) => response,
                Err(ERANGE) => continue,
                Err(error) => return Err(error),
            };

            if let Some(response) = response {
                let response = response?;
                if response.command == expected_command && response.sequence == expected_sequence {
                    return Ok(response);
                }

                dev_dbg!(
                    &dev,
                    "GSP GMC: skip seq {} command 0x{:x}; expected seq {} command 0x{:x}\n",
                    response.sequence,
                    response.command,
                    expected_sequence,
                    expected_command,
                );
            }
        }
    }

    /// Sends a synchronous GMC command whose reply has no payload.
    pub(crate) fn send_gmc_no_response(
        &self,
        bar: Bar0<'_>,
        command_id: u32,
        payload: &[u8],
    ) -> Result {
        let response = self.send_gmc_and_receive(bar, command_id, payload, 0)?;
        if response.status == 0 {
            Ok(())
        } else {
            Err(EIO)
        }
    }

    /// Sends an asynchronous GMC command and waits atomically for its event.
    ///
    /// The command queue remains locked from the send through the matching
    /// event, preventing another transaction from consuming its completion.
    /// Interleaved GMC messages are passed to `handler`. The timeout is shared
    /// by the complete operation.
    pub(crate) fn send_gmc_and_wait_event(
        &self,
        bar: Bar0<'_>,
        command_id: u32,
        payload: &[u8],
        timeout: Delta,
        mut predicate: impl FnMut(u32, u32, u64, &[u8], &[u8]) -> Result<bool>,
        mut handler: impl FnMut(u32, u32, u64, &[u8], &[u8]) -> Result,
    ) -> Result {
        let mut inner = self.inner.lock();
        inner.send_gmc(bar, command_id, payload, 0)?;
        let deadline = Instant::<Monotonic>::now() + timeout;

        loop {
            let remaining = deadline - Instant::<Monotonic>::now();
            if remaining.is_negative() {
                return Err(ETIMEDOUT);
            }

            let matched = match inner.receive_gmc_and_dispatch(
                bar,
                remaining,
                |command, status, sequence, payload_0, payload_1| {
                    let result: Result<bool> = (|| {
                        if predicate(command, status, sequence, payload_0, payload_1)? {
                            return Ok(true);
                        }

                        handler(command, status, sequence, payload_0, payload_1)?;
                        Ok(false)
                    })();
                    (Some(result), QueuePointers::Unchanged)
                },
            ) {
                Ok(matched) => matched,
                Err(ERANGE) => continue,
                Err(error) => return Err(error),
            };

            if let Some(matched) = matched {
                if matched? {
                    return Ok(());
                }
            }
        }
    }

    /// Waits for an unsolicited GSP event of type `M`, dispatching any other event that arrives
    /// first.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if the event does not arrive within [`Self::RECEIVE_TIMEOUT`] of the call,
    ///   however many other events are dispatched while waiting.
    #[expect(dead_code)]
    pub(crate) fn await_msg<M: MessageFromGsp>(&self, bar: Bar0<'_>) -> Result<M>
    where
        // This allows all error types, including `Infallible`, to be used for `M::InitError`.
        Error: From<M::InitError>,
    {
        let deadline = Instant::<Monotonic>::now() + Self::RECEIVE_TIMEOUT;
        loop {
            let remaining = deadline - Instant::<Monotonic>::now();
            if remaining.is_negative() {
                break Err(ETIMEDOUT);
            }
            match self.receive_msg::<M>(bar, remaining) {
                Ok(msg) => break Ok(msg),
                Err(ERANGE) => continue,
                Err(e) => break Err(e),
            }
        }
    }

    /// Drains and dispatches every message currently pending in the GSP-to-CPU queue.
    ///
    /// Dispatches pending RM RPC messages as events, consumes pending GMC messages, and returns
    /// without waiting for more.
    ///
    /// # Errors
    ///
    /// Propagates a receive error, in particular the `EIO` of a queue poisoned by corrupt framing.
    pub(crate) fn drain(&self, bar: Bar0<'_>) -> Result {
        self.inner.lock().drain(bar)
    }
}

/// Inner mutex protected state of [`Cmdq`].
struct CmdqInner {
    /// Device this command queue belongs to.
    dev: ARef<device::Device>,
    /// Next RPC sequence number. The GSP echoes it in a command's reply, which lets
    /// [`CmdqInner::receive_msg`] match that reply to the awaiting command. Advances once per
    /// logical command.
    rpc_seq: u32,
    /// Debug-log sequence for async sends. Those commands do not wait for a reply, so this
    /// counter is the number printed in the send log.
    tx_async_seq: u32,
    /// Debug-log sequence for GSP-initiated events. The GSP leaves the RPC sequence unset on
    /// those messages, so the driver numbers them itself.
    rx_event_seq: u32,
    /// Set once a message with corrupt framing or a bad MCTP magic is seen. Such a message has an
    /// untrusted length, so the queue cannot be advanced past it, and every later receive fails
    /// until the queue is torn down and reset.
    ///
    /// A [`Cell`], so the shared-borrow read path [`Self::wait_for_msg`] can set it.
    poisoned: Cell<bool>,
    /// Memory area shared with the GSP for communicating commands and messages.
    gsp_mem: DmaGspMem,
}

impl CmdqInner {
    /// Timeout for waiting for space on the command queue.
    const ALLOCATE_TIMEOUT: Delta = Delta::from_secs(1);

    /// Sends `command` to the GSP, without splitting it.
    ///
    /// # Errors
    ///
    /// - `EMSGSIZE` if the command exceeds the maximum queue element size.
    /// - `ETIMEDOUT` if space does not become available within the timeout.
    /// - `EIO` if the variable payload requested by the command has not been entirely
    ///   written to by its [`CommandToGsp::init_variable_payload`] method.
    ///
    /// Error codes returned by the command initializers are propagated as-is.
    fn send_single_command<M>(&mut self, bar: Bar0<'_>, command: M, rpc_seq: u32) -> Result
    where
        M: CommandToGsp,
        // This allows all error types, including `Infallible`, to be used for `M::InitError`.
        Error: From<M::InitError>,
    {
        let size_in_bytes = command.size();
        let dst = self
            .gsp_mem
            .allocate_command(bar, size_in_bytes, Self::ALLOCATE_TIMEOUT)?;

        // Extract area for the command itself. The GSP message header and the command header
        // together are guaranteed to fit entirely into a single page, so it's ok to only look
        // at `dst.contents.0` here.
        let (cmd, payload_1) = M::Command::from_bytes_mut_prefix(dst.contents.0).ok_or(EIO)?;

        // Fill the header and command in-place.
        let msg_element = GspMsgElement::init(rpc_seq, size_in_bytes, M::FUNCTION);
        // SAFETY: `msg_header` and `cmd` are valid references, and not touched if the initializer
        // fails.
        unsafe {
            msg_element.__init(core::ptr::from_mut(dst.header))?;
            command.init().__init(core::ptr::from_mut(cmd))?;
        }

        // Fill the variable-length payload, which may be empty.
        let mut sbuffer = SBufferIter::new_writer([&mut payload_1[..], &mut dst.contents.1[..]]);
        command.init_variable_payload(&mut sbuffer)?;

        if !sbuffer.is_empty() {
            return Err(EIO);
        }
        drop(sbuffer);

        if M::IS_ASYNC {
            dev_dbg!(
                &self.dev,
                "GSP RPC: async send: seq# {}, function={:?}, length=0x{:x}\n",
                self.tx_async_seq,
                M::FUNCTION,
                dst.header.length(),
            );
            self.tx_async_seq += 1;
        } else {
            dev_dbg!(
                &self.dev,
                "GSP RPC: send: seq# {}, function={:?}, length=0x{:x}\n",
                rpc_seq,
                M::FUNCTION,
                dst.header.length(),
            );
        }

        // All set - update the write pointer and inform the GSP of the new command.
        let elem_count = dst.header.element_count();
        DmaGspMem::advance_cpu_write_ptr_v2(bar, elem_count);

        Ok(())
    }

    /// Sends `command` to the GSP and returns the RPC sequence number assigned to it.
    ///
    /// The command may be split into multiple messages if it is large. The GSP echoes the
    /// sequence number in the reply, so a caller passes it to [`Self::receive_msg`] to match the
    /// reply to this command.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if space does not become available within the timeout.
    /// - `EIO` if the variable payload requested by the command has not been entirely
    ///   written to by its [`CommandToGsp::init_variable_payload`] method.
    ///
    /// Error codes returned by the command initializers are propagated as-is.
    fn send_command<M>(&mut self, bar: Bar0<'_>, command: M) -> Result<u32>
    where
        M: CommandToGsp,
        Error: From<M::InitError>,
    {
        let rpc_seq = self.rpc_seq;
        self.rpc_seq = self.rpc_seq.wrapping_add(1);

        match SplitState::new(command)? {
            SplitState::Single(command) => self.send_single_command(bar, command, rpc_seq)?,
            SplitState::Split(command, mut continuations) => {
                self.send_single_command(bar, command, rpc_seq)?;

                while let Some(continuation) = continuations.next() {
                    self.send_single_command::<ContinuationRecord<'_>>(bar, continuation, rpc_seq)?;
                }
            }
        }

        Ok(rpc_seq)
    }

    /// Sends a GMC API command to the GSP.
    ///
    /// `command_id` is the GMC command identifier (from `GMCAPI_COMMANDS`).
    /// `payload` is the command-specific data following the [`super::fw::GmcApiHeader`].
    /// `max_response_size` is the maximum expected response payload size.
    ///
    /// The command carries the next RPC sequence number, which the GSP echoes in its response.
    /// The number is consumed whether or not the send succeeds.
    ///
    /// # Errors
    ///
    /// - `EMSGSIZE` if the command exceeds the maximum queue element size.
    /// - `ETIMEDOUT` if space does not become available within the timeout.
    /// - `EIO` if the command header is not properly aligned.
    fn send_gmc(
        &mut self,
        bar: Bar0<'_>,
        command_id: u32,
        payload: &[u8],
        max_response_size: u32,
    ) -> Result<u64> {
        let rpc_seq = self.rpc_seq;
        self.rpc_seq = self.rpc_seq.wrapping_add(1);
        let sequence = u64::from(rpc_seq);

        let dst = self.gsp_mem.allocate_command::<GspGmcMsgElement>(
            bar,
            payload.len(),
            Self::ALLOCATE_TIMEOUT,
        )?;

        let msg_element = GspGmcMsgElement::init(
            command_id,
            sequence,
            payload.len(),
            max_response_size,
        );
        // SAFETY: `dst.header` points to a valid, writable `GspGmcMsgElement` region.
        unsafe {
            msg_element.__init(core::ptr::from_mut(dst.header))?;
        }

        SBufferIter::new_writer([&mut dst.contents.0[..], &mut dst.contents.1[..]])
            .write_all(payload)?;

        dev_dbg!(
            &self.dev,
            "GSP GMC: send: seq# {}, command_id=0x{:x}, length=0x{:x}\n",
            sequence,
            command_id,
            dst.header.length(),
        );

        let elem_count = dst.header.element_count();
        DmaGspMem::advance_cpu_write_ptr_v2(bar, elem_count);

        Ok(sequence)
    }

    /// Wait for a message to become available on the message queue.
    ///
    /// This works purely at the transport layer and does not interpret or validate the message
    /// beyond the advertised length in its [`GspMsgElement`].
    ///
    /// This method returns:
    ///
    /// - A reference to the [`GspMsgElement`] of the message,
    /// - Two byte slices with the contents of the message. The second slice is empty unless the
    ///   message loops across the message queue.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if `timeout` has elapsed before any message becomes available.
    /// - `EIO` if the framing or the checksum is invalid, or the queue was already poisoned by an
    ///   earlier such failure. Either failure poisons the queue, so recovery requires a reset.
    fn wait_for_msg(&self, bar: Bar0<'_>, timeout: Delta) -> Result<GspMessage<'_>> {
        if self.poisoned.get() {
            return Err(EIO);
        }

        // Wait for a message to arrive from the GSP.
        let (slice_1, slice_2) = read_poll_timeout(
            || Ok(self.gsp_mem.driver_read_area_v2(bar)),
            |driver_area| !driver_area.0.is_empty(),
            Delta::from_millis(1),
            timeout,
        )
        .map(|(slice_1, slice_2)| (slice_1.as_flattened(), slice_2.as_flattened()))?;

        // Extract the `GspMsgElement`.
        let Some((header, slice_1)) = GspMsgElement::from_bytes_prefix(slice_1) else {
            self.poisoned.set(true);
            return Err(EIO);
        };

        // Check the common framing before interpreting RPC-specific lengths or fields.
        if !header.has_valid_magic() || !header.is_rm_rpc() {
            dev_err!(&self.dev, "GSP RPC: receive: invalid MCTP/NVDM framing\n");
            self.poisoned.set(true);
            return Err(EIO);
        }

        let payload_length = header.payload_length();

        // Check that the driver read area is large enough for the message.
        if slice_1.len() + slice_2.len() < payload_length {
            self.poisoned.set(true);
            return Err(EIO);
        }

        // Cut the message slices down to the actual length of the message.
        let (slice_1, slice_2) = if slice_1.len() > payload_length {
            // PANIC: we checked above that `slice_1` is at least as long as `payload_length`.
            (slice_1.split_at(payload_length).0, &slice_2[0..0])
        } else {
            (
                slice_1,
                // PANIC: we checked above that `slice_1.len() + slice_2.len()` is at least as
                // large as `payload_length`.
                slice_2.split_at(payload_length - slice_1.len()).0,
            )
        };

        Ok(GspMessage {
            header,
            contents: (slice_1, slice_2),
        })
    }

    /// Writes the classified receive debug line for a decoded GSP message.
    ///
    /// Events print [`Self::rx_event_seq`]. Command replies print `seq`. An unrecognized function
    /// code prints nothing here.
    fn log_received(&self, function: Result<MsgFunction, u32>, seq: u32, length: usize) {
        match function {
            Ok(f) if f.is_event() => {
                dev_dbg!(
                    &self.dev,
                    "GSP RPC: async received: seq# {}, function={:?}, length=0x{:x}\n",
                    self.rx_event_seq,
                    f,
                    length,
                );
            }
            Ok(f) => {
                dev_dbg!(
                    &self.dev,
                    "GSP RPC: response received: seq# {}, function={:?}, length=0x{:x}\n",
                    seq,
                    f,
                    length,
                );
            }
            Err(_) => {}
        }
    }

    /// Advances [`Self::rx_event_seq`] after a GSP-initiated event has been consumed.
    fn advance_rx_event_seq(&mut self, function: Result<MsgFunction, u32>) {
        if matches!(function, Ok(f) if f.is_event()) {
            self.rx_event_seq += 1;
        }
    }

    /// Consumes and dispatches the RM RPC element currently at the queue head.
    fn consume_and_dispatch_rpc(&mut self, bar: Bar0<'_>) -> Result {
        let (function, seq, length) = {
            let message = self.wait_for_msg(bar, Delta::ZERO)?;

            (
                message.header.function(),
                message.header.sequence(),
                message.header.length(),
            )
        };

        self.log_received(function, seq, length);
        let pages = u32::try_from(length.div_ceil(GSP_PAGE_SIZE))?;
        DmaGspMem::advance_cpu_read_ptr_v2(bar, pages);
        self.advance_rx_event_seq(function);
        self.dispatch_event(function, seq);
        Ok(())
    }

    /// Receive a message from the GSP.
    ///
    /// The expected message type is given by the `M` generic parameter. With `expected_seq` set,
    /// the message must also carry that RPC sequence number to count as the awaited reply. With
    /// `None`, the function code alone decides the match.
    ///
    /// A matching message is decoded and returned. A message carrying the expected function code
    /// with a different sequence is a stale reply to a command that already timed out, and is
    /// logged and dropped. Any other message goes to [`Self::dispatch_event`]. Both non-matching
    /// cases return `ERANGE`.
    ///
    /// The read pointer is always advanced past the message, regardless of whether it matched.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if `timeout` has elapsed before any message becomes available.
    /// - `EIO` if the queue is poisoned or the message fails framing or checksum validation (see
    ///   [`Self::wait_for_msg`]), or if the matched message is too short for `M::Message`.
    /// - `ERANGE` if the message was not the awaited reply.
    ///
    /// Error codes returned by [`MessageFromGsp::read`] are propagated as-is.
    fn receive_msg<M: MessageFromGsp>(
        &mut self,
        bar: Bar0<'_>,
        timeout: Delta,
        expected_seq: Option<u32>,
    ) -> Result<M>
    where
        // This allows all error types, including `Infallible`, to be used for `M::InitError`.
        Error: From<M::InitError>,
    {
        let message = self.wait_for_msg(bar, timeout)?;
        let function = message.header.function();
        let seq = message.header.sequence();
        let length = message.header.length();
        let func_matches = matches!(function, Ok(f) if f == M::FUNCTION);
        let matched = func_matches && expected_seq.is_none_or(|expected| seq == expected);

        self.log_received(function, seq, length);

        // Every path must advance the read pointer past this message, including a failed decode.
        let result = if matched {
            match M::Message::from_bytes_prefix(message.contents.0) {
                Some((cmd, contents_1)) => {
                    let mut sbuffer = SBufferIter::new_reader([contents_1, message.contents.1]);

                    M::read(cmd, &mut sbuffer)
                        .map_err(|e| e.into())
                        .inspect(|_| {
                            if !sbuffer.is_empty() {
                                dev_warn!(
                                    &self.dev,
                                    "GSP message {:?} has unprocessed data\n",
                                    M::FUNCTION
                                );
                            }
                        })
                }
                None => Err(EIO),
            }
        } else {
            Err(ERANGE)
        };

        // Advance the read pointer past this message.
        DmaGspMem::advance_cpu_read_ptr_v2(bar, u32::try_from(length.div_ceil(GSP_PAGE_SIZE))?);

        self.advance_rx_event_seq(function);

        if !matched {
            if func_matches {
                dev_warn!(
                    &self.dev,
                    "GSP RPC: dropping stale {:?} reply (seq {}, awaiting {:?})\n",
                    M::FUNCTION,
                    seq,
                    expected_seq,
                );
            } else {
                self.dispatch_event(function, seq);
            }
        }

        result
    }

    /// Routes a GSP message that is not the reply a caller is waiting for.
    ///
    /// GSP-reported errors are logged at error level and unrecognized function codes at warning
    /// level. Every other known function code is consumed without a log line, because
    /// [`Self::log_received`] already records its arrival.
    fn dispatch_event(&self, function: Result<MsgFunction, u32>, seq: u32) {
        match function {
            Ok(MsgFunction::OsErrorLog) => {
                dev_err!(&self.dev, "GSP reported an OS error (seq {})\n", seq);
            }
            Ok(MsgFunction::RcTriggered) => {
                dev_err!(
                    &self.dev,
                    "GSP triggered robust-channel recovery (seq {})\n",
                    seq
                );
            }
            // GSP logs, libos prints, NoCat assertion records, and the other known event codes.
            // None of them requires action.
            Ok(_) => {}
            Err(raw) => {
                dev_warn!(
                    &self.dev,
                    "unknown GSP message function {:#x} (seq {})\n",
                    raw,
                    seq
                );
            }
        }
    }

    /// Drains and dispatches all messages currently pending in the GSP-to-CPU queue.
    ///
    /// RM RPC messages are dispatched as events. GMC messages are unsolicited while the drain owns
    /// the command queue lock, so they are consumed without dispatch.
    ///
    /// # Errors
    ///
    /// Returns the receive error that stopped the drain, in particular the `EIO` of a queue
    /// poisoned by framing that is invalid for both GMC and RM RPC (see
    /// [`Self::receive_gmc_and_dispatch`]).
    fn drain(&mut self, bar: Bar0<'_>) -> Result {
        while !self.gsp_mem.driver_read_area_v2(bar).0.is_empty() {
            match self.receive_gmc_and_dispatch::<()>(
                bar,
                Delta::ZERO,
                |_, _, _, _, _| (None, QueuePointers::Unchanged),
            ) {
                Ok(_) | Err(ERANGE) => {}
                Err(error) => return Err(error),
            }
        }

        Ok(())
    }

    /// Wait for a GMC message to become available on the message queue.
    ///
    /// This is the GMC counterpart to [`Self::wait_for_msg`] and reads the same queue. Like that
    /// method it works purely at the transport layer, validating the MCTP framing and the
    /// advertised length and nothing else.
    ///
    /// A [`GspGmcMsgElement`] and a [`GspMsgElement`] share every field through `nvdm_header`,
    /// so a caller that may see either must check the NVDM type before reading `gmc`. Both
    /// layouts put the element length in the same place, so the caller can advance the read
    /// pointer past a returned message either way.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if `timeout` has elapsed before any message becomes available.
    /// - `EIO` if the framing is invalid, or the queue was already poisoned by an earlier such
    ///   failure. Either failure poisons the queue, so recovery requires a reset.
    fn wait_for_gmc_msg(&self, bar: Bar0<'_>, timeout: Delta) -> Result<GmcMessage<'_>> {
        if self.poisoned.get() {
            return Err(EIO);
        }

        let (slice_1, slice_2) = read_poll_timeout(
            || Ok(self.gsp_mem.driver_read_area_v2(bar)),
            |driver_area| !driver_area.0.is_empty(),
            Delta::from_millis(1),
            timeout,
        )
        .map(|(slice_1, slice_2)| (slice_1.as_flattened(), slice_2.as_flattened()))?;

        let Some((header, slice_1)) = GspGmcMsgElement::from_bytes_prefix(slice_1) else {
            self.poisoned.set(true);
            return Err(EIO);
        };

        // Checked before any length field is read, since a bad magic leaves them untrusted.
        if !header.has_valid_magic() {
            dev_err!(&self.dev, "GSP GMC: receive: bad MCTP magic\n");
            self.poisoned.set(true);
            return Err(EIO);
        }

        let payload_length = header.payload_length();

        // Check that the driver read area is large enough for the message.
        if slice_1.len() + slice_2.len() < payload_length {
            self.poisoned.set(true);
            return Err(EIO);
        }

        // Cut the message slices down to the actual length of the message.
        let (slice_1, slice_2) = if slice_1.len() > payload_length {
            // PANIC: we checked above that `slice_1` is at least as long as `payload_length`.
            (slice_1.split_at(payload_length).0, &slice_2[0..0])
        } else {
            (
                slice_1,
                // PANIC: we checked above that `slice_1.len() + slice_2.len()` is at least as
                // large as `payload_length`.
                slice_2.split_at(payload_length - slice_1.len()).0,
            )
        };

        Ok(GmcMessage {
            header,
            contents: (slice_1, slice_2),
        })
    }

    /// Receive the next GMC event from the GSP and dispatch it through a handler.
    ///
    /// The handler receives the GMC command id, the header's `max_resp_or_status` field, and the
    /// raw payload slices that follow the [`super::fw::GmcApiHeader`] (two slices because the
    /// circular buffer may wrap). It returns `None` for an element it does not handle, paired
    /// with the [`QueuePointers`] state it left behind.
    ///
    /// `max_resp_or_status` is a union: GSP-RM writes an `NV_STATUS` there when the element is a
    /// response, and the maximum response size when it is a request. Only a handler that knows
    /// which one it asked for can read it.
    ///
    /// Where [`Self::receive_msg`] keys on [`MsgFunction`], this keys on the GMC command id,
    /// which is the form the r000 firmware uses for boot events.
    ///
    /// Returns `Ok(None)` when the handler declines a GMC element. A valid interleaved RM RPC
    /// element is consumed and dispatched before this method returns `ERANGE`. The read pointer is
    /// advanced past the element on every path except a handler reporting [`QueuePointers::Reset`],
    /// which has already returned both pointers to zero.
    ///
    /// # Errors
    ///
    /// - `ETIMEDOUT` if `timeout` has elapsed before any message becomes available.
    /// - `EIO` if the queue is poisoned or the element fails framing validation (see
    ///   [`Self::wait_for_gmc_msg`]).
    /// - `ERANGE` if a valid interleaved RM RPC element was consumed and dispatched.
    fn receive_gmc_and_dispatch<R>(
        &mut self,
        bar: Bar0<'_>,
        timeout: Delta,
        handler: impl FnOnce(u32, u32, u64, &[u8], &[u8]) -> (Option<R>, QueuePointers),
    ) -> Result<Option<R>> {
        let message = self.wait_for_gmc_msg(bar, timeout)?;
        if !message.header.is_gmc_api() {
            self.consume_and_dispatch_rpc(bar)?;
            return Err(ERANGE);
        }

        let header = message.header;
        let length = header.length();

        // A handler that resets the GSP zeroes both of these, and the values they hold now are
        // the ones the driver has to put back.
        let cpu_write_ptr = DmaGspMem::cpu_write_ptr_v2(bar);
        let cpu_read_ptr = DmaGspMem::cpu_read_ptr_v2(bar);

        let command_id = header.gmc.command_id();
        let sequence = header.gmc.sequence;

        dev_dbg!(
            &self.dev,
            "GSP GMC: event: seq# {}, command_id=0x{:x}, length=0x{:x}\n",
            sequence,
            command_id,
            length,
        );

        let (result, queue_pointers) = handler(
            command_id,
            header.gmc.max_resp_or_status,
            sequence,
            message.contents.0,
            message.contents.1,
        );

        let pages = u32::try_from(length.div_ceil(GSP_PAGE_SIZE))?;

        match queue_pointers {
            QueuePointers::Unchanged => DmaGspMem::advance_cpu_read_ptr_v2(bar, pages),
            // The registers read zero now, so a read-modify-write would restart the driver's
            // side of the ring at zero while GSP-RM carries on from where it stopped. Put the
            // captured values back instead, with this element counted as consumed.
            QueuePointers::Reset => {
                DmaGspMem::restore_cpu_ptrs_v2(bar, cpu_write_ptr, cpu_read_ptr.wrapping_add(pages))
            }
        }

        Ok(result)
    }
}
