// SPDX-License-Identifier: GPL-2.0

//! C-compatible descriptors for calls into Rust.
//!
//! An FFI descriptor contains an operations table plus an opaque, pinned Rust context. This
//! module deliberately does not publish the descriptor or manage its lifetime. A transport, such
//! as PCI SR-IOV, must keep the context alive and pinned for as long as a consumer can call through
//! the descriptor.

use crate::{
    bindings,
    types::{
        CovariantForLt,
        ForLt, //
    },
};
use core::{
    ffi::c_void,
    pin::Pin, //
};

/// A transport-independent token identifying an FFI ABI.
///
/// Consumers compare this token before interpreting an opaque operations-table pointer. It is an
/// ABI type tag, not a device identifier, secret, authorization capability, or lifetime handle.
///
/// This is a transparent wrapper around
/// [`struct rust_ffi_token`](srctree/include/linux/rust_ffi.h).
#[derive(Clone, Copy)]
#[repr(transparent)]
pub struct Token(bindings::rust_ffi_token);

impl Token {
    /// Creates an FFI token from its most and least significant halves.
    pub const fn new(high: u64, low: u64) -> Self {
        Self(bindings::rust_ffi_token { high, low })
    }

    /// Returns the most significant half of the token.
    pub const fn high(self) -> u64 {
        self.0.high
    }

    /// Returns the least significant half of the token.
    pub const fn low(self) -> u64 {
        self.0.low
    }
}

impl PartialEq for Token {
    fn eq(&self, other: &Self) -> bool {
        self.high() == other.high() && self.low() == other.low()
    }
}

impl Eq for Token {}

/// Defines the identity, Rust context, and raw operations-table type of an FFI ABI.
///
/// Implementations are normally paired with an operations table generated by [`ffi_vtable`]. The
/// Rust provider and every C consumer must share the corresponding C definition.
///
/// [`ffi_vtable`]: crate::macros::ffi_vtable
///
/// # Safety
///
/// Implementers must ensure that:
///
/// - [`RawOps`](Self::RawOps) has a stable C-compatible layout and [`OPS`](Self::OPS) is a fully
///   initialized instance of that layout;
/// - for every possible data lifetime, every callback in `OPS` interprets its context as a pinned
///   [`ForLt::Of`] value with that lifetime, only borrows it for the duration of the callback, and
///   does not leak or otherwise extend references derived from it;
/// - [`TOKEN`](Self::TOKEN) and the ABI version uniquely identify that layout and its semantics;
///   and
/// - changing `RawOps` incompatibly also changes the ABI major version.
pub unsafe trait Abi: 'static {
    /// Rust context type expected by the operations-table callbacks.
    type Context: CovariantForLt + 'static;

    /// Raw C-compatible operations-table type.
    type RawOps: Sync + 'static;

    /// Static operations table published for this ABI.
    const OPS: &'static Self::RawOps;

    /// Token shared by providers and consumers of this FFI ABI.
    const TOKEN: Token;

    /// ABI major version, incremented for incompatible changes.
    const ABI_MAJOR: u16;

    /// ABI minor version, incremented for compatible extensions.
    const ABI_MINOR: u16;
}

/// A C-compatible descriptor for an opaque Rust context and operations table.
///
/// This is a transparent wrapper around
/// [`struct rust_ffi`](srctree/include/linux/rust_ffi.h). It neither owns nor borrows the
/// operations table or Rust context at the type level. The transport that publishes it must ensure
/// that `ops` remains valid and that `context` remains alive at a stable address until all
/// consumers have stopped using the descriptor. The default value exposes no operations.
#[repr(transparent)]
pub struct Descriptor(bindings::rust_ffi);

impl Default for Descriptor {
    fn default() -> Self {
        Self(bindings::rust_ffi {
            token: bindings::rust_ffi_token { high: 0, low: 0 },
            abi_major: 0,
            abi_minor: 0,
            ops_size: 0,
            ops: core::ptr::null(),
            context: core::ptr::null(),
        })
    }
}

impl Descriptor {
    /// Creates a descriptor for a pinned Rust context.
    ///
    /// The descriptor does not retain the provider's Rust type or lifetime. A transport must not
    /// publish it for longer than `context` remains alive and pinned.
    pub fn new<'borrow, 'data, A>(context: Pin<&'borrow <A::Context as ForLt>::Of<'data>>) -> Self
    where
        A: Abi,
        for<'b> <A::Context as ForLt>::Of<'b>: Send + Sync,
    {
        Self(bindings::rust_ffi {
            token: A::TOKEN.0,
            abi_major: A::ABI_MAJOR,
            abi_minor: A::ABI_MINOR,
            ops_size: core::mem::size_of::<A::RawOps>(),
            ops: core::ptr::from_ref(A::OPS).cast(),
            context: core::ptr::from_ref(context.get_ref()).cast(),
        })
    }

    /// Returns the FFI ABI token.
    pub const fn token(&self) -> Token {
        Token(self.0.token)
    }

    /// Returns the FFI ABI major version.
    pub const fn abi_major(&self) -> u16 {
        self.0.abi_major
    }

    /// Returns the FFI ABI minor version.
    pub const fn abi_minor(&self) -> u16 {
        self.0.abi_minor
    }

    /// Returns the size in bytes of the raw operations table.
    pub const fn ops_size(&self) -> usize {
        self.0.ops_size
    }

    /// Returns the operations-table pointer.
    pub const fn ops(&self) -> *const c_void {
        self.0.ops
    }

    /// Returns the provider-context pointer.
    pub const fn context(&self) -> *const c_void {
        self.0.context
    }

    /// Returns a raw pointer to the underlying C descriptor.
    pub const fn as_raw(&self) -> *const bindings::rust_ffi {
        core::ptr::from_ref(&self.0)
    }
}

/// Implementation details for generated FFI adapters.
#[doc(hidden)]
pub mod __private {
    use crate::{
        error::{
            from_result,
            Result, //
        },
        ffi::c_int, //
    };
    use core::{
        ffi::c_void,
        pin::Pin, //
    };

    mod sealed {
        use super::{
            c_int,
            Result, //
        };

        pub trait Sealed<C> {}

        impl<T> Sealed<T> for T {}
        impl Sealed<c_int> for Result<()> {}
        impl Sealed<c_int> for Result<c_int> {}
    }

    /// Converts a Rust operation return value into the return type of its C callback.
    ///
    /// The C return type is supplied by the raw operations-table field. This trait is sealed so
    /// generated adapters can select only the conversions defined by this module.
    pub trait FfiReturn<C>: sealed::Sealed<C> {
        /// Performs the return-value conversion.
        fn into_ffi(self) -> C;
    }

    impl<T> FfiReturn<T> for T {
        #[inline]
        fn into_ffi(self) -> T {
            self
        }
    }

    impl FfiReturn<c_int> for Result<()> {
        #[inline]
        fn into_ffi(self) -> c_int {
            from_result(|| self.map(|()| 0))
        }
    }

    impl FfiReturn<c_int> for Result<c_int> {
        #[inline]
        fn into_ffi(self) -> c_int {
            from_result(|| self)
        }
    }

    /// Recovers a pinned Rust reference from an opaque FFI context pointer.
    ///
    /// # Safety
    ///
    /// `context` must have been obtained from a `Pin<&T>` and must point to a live, properly
    /// aligned `T` that remains pinned and valid for shared access for the entire returned
    /// lifetime. The pointed-to value must not be mutated except through synchronization-safe
    /// interior mutability.
    pub unsafe fn borrow_context<'a, T: 'a>(context: *const c_void) -> Pin<&'a T> {
        // SAFETY: The caller guarantees that `context` is a valid shared pointer to a pinned `T`
        // for the caller-selected lifetime `'a`.
        unsafe { Pin::new_unchecked(&*context.cast::<T>()) }
    }
}
